### ISSUE TITLE
workspace/symbol & textDocument/documentSymbol

### ISSUE THREAD

**Issue by damieng** [atom/atom-languageclient#10]
[Project](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspace_symbol) and [document](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_documentSymbol) level symbols are available in the LSP.

Today we have the symbols package in Atom which is heavily tied to ctags and provides no UI of it's own and the outline view in Nuclide which exposes a UI that is not well suited to the data returned from LSP.

## Experience
- A shortcut key to toggle the view 
- The view by default shows just a document outline
- A second shortcut key to search for a symbol (replaces existing symbol-view shortcut)
- Brings this view in if not currently shown and focuses in the search box selecting all current search text (so it can be easily overwritten/cleared)
- Typing filters the results in the outline view/symbol portion
- Arrow up/down allows user to select a symbol
- Enter goes to that symbol and will also hide the view if it was not previously visible

For workspace either a toggle, additional shortcut or some kind of combined/visual indicator should be considered. TBD.

**Comment by ljw1004** [comment]
I think the outline view is actually well suited to the data returned from LSP! The textDocument/documentSymbols verb gives us back a list of symbols with their parent names. If we assume that a container symbol comes lexically before the symbols inside it (as they do in all LSP languages, including even C/C++) then we can reconstruct the OutlineView correctly. The SymbolInfo.kind field gives a good icon to display in OutlineView too.

**Comment by hansonw** [comment]
see @ljw1004's implementation for our internal LSP adapter: 

https://github.com/facebook/nuclide/commit/dc59da7fec59cc48f4140de493beb7a151523598 (tree structure)
https://github.com/facebook/nuclide/commit/d734d342b7bc8708b2d35e80adfff053636ad9e9 (icons)

**Comment by damieng** [comment]
With the icon support it might be useful although I still think we're going to need go-to-symbol support for both the project and the current document. The latter might be do-able with further changes to outline view?  Any thoughts on the former?

**Comment by ljw1004** [comment]
For the project-wide symbol search, Nuclide uses a "symbols" tab in the quick-open dialog. I've hooked it up so that LSP calls to workspace/symbol can populate it.

Oh gosh I really love the quick-open dialog. I've found it so incredibly useful, much friendlier than the symbol-search functionality in VSCode and VisualStudio. I love how it conveniently aggregates *all* the relevant search mechanisms in an easily-discoverable way, so it educates me about other search mechanisms I wasn't aware of, and it removes the up-front brain tax of having to decide which search mechanism to use (e.g. document-search vs project-search in VSCode).

**Comment by damieng** [comment]
documentSymbols now wired up to the revised Outline view using enhanced logic + syntax coloring + icons.  Will create a separate issue for project symbols.

**Comment by hansonw** [comment]
`atom-ide-ui` 0.1.6+ has a searchable outline view now :) Still doesn't address project symbols, but it should help bridge the gap between symbols-view/outline-view.

![screen shot 2017-06-19 at 3 02 58 pm](https://user-images.githubusercontent.com/577378/27307820-6f9395c4-5500-11e7-8249-442d87bebd35.png)

**Comment by ryanolsonx** [comment]
Where's the issue for project symbols? I might dig into exposing that data.
