### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by bhack** [atom/atom-languageclient#104]
Do you plan to support [Clangd](https://clang.llvm.org/extra/clangd.html)?

**Comment by damieng** [comment]
If anyone wants to create an ide-cpp package or something similar we'd certainly offer support to them.

We unfortunately do not have the resources to write these packages ourselves at this time.

**Comment by bhack** [comment]
@thomasjo is "anyone" 😄  https://github.com/thomasjo/atom-ide-cpp

**Comment by thomasjo** [comment]
@bhack Yes, I have started working on this. Hopefully it'll be possible to bundle it with the package at some point in the future. For now it will require manually building LLVM, Clang and Clangd from source.

**Comment by bhack** [comment]
@thomasjo I see the Vscode ide [client code](https://github.com/llvm-mirror/clang-tools-extra/tree/master/clangd/clients/clangd-vscode) is maintained directly in the upstream repository. Was the officially testing client?

**Comment by bhack** [comment]
I think in the meantime we could reccomend https://apt.llvm.org on linux

**Comment by thomasjo** [comment]
@bhack They are just using VS code as test bed. The extension in the Clangd source tree is just a very minimal example being used to test end-to-end integration.

There's currently some problems with the nightly builds on [apt.llvm.org](http://apt.llvm.org/), but yes, as long as users install a nightly build of Clang, they should get an up-to-date Clangd. However, note that the way Clangd has been shipped in 5.0 repository, means it doesn't work at all. The only way I could get functional and up-to-date Clangd was to build from the SVN repositories.

Regardless, let's continue this discussion on Slack (or somewhere else). We use issues as a backlog of actionable items, and we are misusing it right now.
