### ISSUE TITLE
startServerProcess () {} not firing

### ISSUE THREAD

**Issue by aroach** [atom/atom-languageclient#107]
I've never created an Atom plugin before, so this could be a newbie question...

I'm working on an ide integration for YANG models (https://github.com/yang-tools/yang-lsp)

When I switch to a .yang file, the plugin doesn't seem to actually fire the startServerProcess().  I have a console.log in my library's startServerProcess() function.  

It seems like the plugin is loading when Atom starts up, as I have a console log statement that displays in the developer tools.  I've also enabled the language server debugging in Atom config.  That seems to work for the ide-java package, for example.

I've registered "source.yang" in both the package.json and in the `getGrammarScopes () { return [ 'source.yang' ] }` method.  

Any tips on troubleshooting this would be welcome.

Edit: Here's my code if helpful https://github.com/aroach/ide-yang

**Comment by damieng** [comment]
You'll also need a language grammar which is responsible for detecting the file type and performing the syntax highlighting.

Thankfully one already appears to exist for yang so you should just need to install it via apm https://github.com/DzonyKalafut/language-yang

**Comment by aroach** [comment]
Ah ha!  Let me check that out.  Is there a way to include that as a dependency programmatically?

**Comment by aroach** [comment]
Great, startServerProcess is now triggering.  Thanks!

**Comment by damieng** [comment]
@aroach there is unfortunately not a way of declaring that. You could potentially try looking for it in the atom.grammars collection and put up a warning notification if you don't find it.
