### ISSUE TITLE
 textDocument/codeLens

### ISSUE THREAD

**Issue by damieng** [atom/atom-languageclient#11]
Need to determine how these can integrate with Atom.

**Comment by wbinnssmith** [comment]
@seansegal implemented code actions over LSP in Nuclide (technically atom-ide-ui, which is BSD+Patents) :D

cc @hansonw

**Comment by damieng** [comment]
How do I see this in action?

**Comment by hansonw** [comment]
Code actions are still a WIP but basically we have them wired up to Diagnostics so you can see inline actions for a diagnostic. Sean worked on a JavaScript auto-imports LSP :D here's a screenshot of the current UI:

![screen shot 2017-08-24 at 4 42 04 pm](https://user-images.githubusercontent.com/577378/29693556-3e0543a8-88eb-11e7-82e2-e719eabab6c3.png)

**Comment by hansonw** [comment]
Gonna separate these two. @captbaritone has a prototype for code lenses internally that we can hopefully ship in `atom-ide-ui` once finished.

**Comment by damieng** [comment]
@hansonw Where are we at with this in atom-ide-ui?  Do I just need to write an adapter?

**Comment by hansonw** [comment]
Nope, we haven't really prioritized working on this due to the lack of providers in this area (do you know any good ones to test with?)

**Comment by rianneogi** [comment]
https://github.com/cquery-project/cquery provides codelens support. (if you are still looking)

**Comment by alexheretic** [comment]
RLS is just starting to make use of codelens for test running, so supporting it would be a valuable addition for ide-rust.
