### ISSUE TITLE
Completion Proposal with no `insertText` and with `label`

### ISSUE THREAD

**Issue by BoykoAlex** [atom/atom-languageclient#110]
Currently if there is no `insertText` specified `languageclient` just takes the `label`.
Our extension has some "help" kind of completions that instead providing text to insert provide a help message in the label and empty text `insertText`. The "help" proposal could simply urge the user to connect to internet to get completion proposal (i.e. explain why there are no completions available.
Currently behaviour of `languageclient` would simply insert a `label` of such proposal into the document because of https://github.com/atom/atom-languageclient/blob/master/lib/adapters/autocomplete-adapter.js#L96
Wonder if could distinguish between `item.insertText` being an empty `string` rather than `undefined`...
For example make that line of code: `text: item.insertText === undefined ? item.label : item.insertText,`

**Comment by damieng** [comment]
I'm wondering why we fall back to the label at all. Nothing in the LSP spec seems to indicate this was a good idea.

**Comment by BoykoAlex** [comment]
Thought that other language server extensions might rely on this behaviour... But if it's not the case lets not fallback on the label :-)

**Comment by damieng** [comment]
Also a problem in https://github.com/atom/ide-java/issues/10

**Comment by nwolverson** [comment]
I think the previous behaviour was per the spec (which vscode implementation follows)
```
	/**
	 * A string that should be inserted a document when selecting
	 * this completion. When `falsy` the label is used.
	 */
	insertText?: string;
```
It seems like the justification above should be directed at the spec if it is persuasive.

(This change bit me but easy enough to work around)

**Comment by damieng** [comment]
Hmm, not sure how I missed that!  Looks like we'll have to go back to the previous behaviour.
