### ISSUE TITLE
Cannot find module 'atom-languageclient' despite atom-languageclient listed as dependency and apm install being run

### ISSUE THREAD

**Issue by JonasT** [atom/atom-languageclient#112]
I am getting an error "Cannot find module 'atom-languageclient'" despite atom-languageclient listed as dependency and apm install being run.

This is the full steps to reproduce on a fresh atom install on Linux:

1. `cd ~/.atom/packages`
2. `git clone https://gitlab.com/tethercode/atom-language-plugin ./language-tethercode`
3. `cd language-tethercode && apm install .`
4. Launch atom and open a file ending with `.tc` ending

Tested on Atom 1.20.1 on Fedora 26 Linux x64

**Comment by JonasT** [comment]
@damieng I think this is #16 occuring again, since the installed package seems to lack the "lib" folder once again.

I suggest that you find a more reliable way to avoid that happening (e.g. with an automated build that checks this and sends an e-mail when a commit breaks it again), or fix the README to correctly state a working install procedure for when this happens.

**Comment by damieng** [comment]
I don't think it's #16 - that was very specifically caused by atom-languageclient not yet being published which is no longer the case.

Is there an atom-languageclient folder in node_modules inside the language-tethercode folder?

If not what happens when you `npm i` in the language-tethercode folder?

**Comment by damieng** [comment]
Oh, I see the problem there.

    "atom-languageclient": "git://github.com/atom/atom-languageclient.git"

Should not be referring to git any more but the latest version number so it can get it from apm.

**Comment by JonasT** [comment]
Thanks, it works now :heart:
