### ISSUE TITLE
Completion items with same text are dropped

### ISSUE THREAD

**Issue by nwolverson** [atom/atom-languageclient#113]
If a language server returns multiple completions that get mapped to the same `text` (but say with different documentation, command/additional edits), some are dropped due to https://github.com/atom/autocomplete-plus/issues/615 - raising here as workarounds have been discussed (that issue and https://github.com/atom/autocomplete-plus/pull/877) - having used one workaround for this which is imperfect I'd rather see an upstream fix.

**Comment by damieng** [comment]
Will be in the next patch release of Atom 1.12 https://github.com/atom/autocomplete-plus/issues/615

**Comment by nwolverson** [comment]
Verified this works with the latest tagged autocomplete-plus.

Super fast change on a long-standing issue! So happy.

**Comment by damieng** [comment]
Yeah glad that worked out for you. It was actually a very simple change although I'm not 100% convinced it won't upset somebody when the suggestion provider they are using doesn't do its own duplication detection hence the config switch :)
