### ISSUE TITLE
Outline view structure not working correctly for some language servers

### ISSUE THREAD

**Issue by lgeiger** [atom/atom-languageclient#116]
First of all thanks for the great work on Atom-IDE! I'm very exited so I started working on a Atom-IDE python package: https://github.com/lgeiger/ide-python

Though I've been struggling with getting the outline view properly structured.

## Problem
The symbol end position returned by the python language server is only the [start position plus the length of the symbol/word](https://github.com/palantir/python-language-server/blob/a1bbd401621f8fc3083f4341b7912b491e82bf68/pyls/plugins/symbols.py#L23):
```python
{
    'start': {'line': d.line - 1, 'character': d.column},
    'end': {'line': d.line - 1, 'character': d.column + len(d.name)}
}
```

Consequently this will mess up the tree mapping:
https://github.com/atom/atom-languageclient/blob/2d11021f8de689d584ffd17d0631721bd1e45e13/lib/adapters/outline-view-adapter.js#L113-L123

and in return the outline view:
<img width="648" alt="incorrect" src="https://user-images.githubusercontent.com/13285808/30942453-90ded6c8-a3eb-11e7-87af-333a280fca42.png">

The correct view would be:
<img width="651" alt="correct" src="https://user-images.githubusercontent.com/13285808/30942452-90dc1cee-a3eb-11e7-8aee-8ad4920d0403.png">

## Possible solutions

1. Don't rely on the end position to determine which the parent symbol and remove the checks [here](https://github.com/atom/atom-languageclient/blob/2d11021f8de689d584ffd17d0631721bd1e45e13/lib/adapters/outline-view-adapter.js#L116) and [here](https://github.com/atom/atom-languageclient/blob/2d11021f8de689d584ffd17d0631721bd1e45e13/lib/adapters/outline-view-adapter.js#L121)

2. Don't return a end position from the language server and don't require it here:
https://github.com/atom/atom-languageclient/blob/2d11021f8de689d584ffd17d0631721bd1e45e13/lib/adapters/outline-view-adapter.js#L149 

I'm happy to make PRs to fix this though I'm very new to the language server protocol so I would appreciate feedback on which would be the preferred solution.

**Comment by Arcanemagus** [comment]
Option 2 isn't valid, a [`textDocument/documentSymbol`](https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#document-symbols-request) request returns a `SymbolInformation`, which contains a [`Location`](https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#location), containing a [`Range`](https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#range) which requires an end [`Position`](https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#position).

**Comment by lgeiger** [comment]
@Arcanemagus Thanks for the explanation. 

In that case what about additionally allowing start and end position to have the same line number, instead of completely removing the check?

**Comment by damieng** [comment]
So from what I can tell the Python language server is thinking in terms of symbols rather than constructs?  i.e. it doesn't say function init runs from line 1 to 10 and but rather says it runs from the start of the token __init__ until the end.

It doesn't look like the spec is particularly clear here but doing that can easily lead to confusing cases in many languages.  e.g. in C# the constructor has the same name as the class so defining ```

```csharp
class Bob {
  Bob() {
   // This is my constructor
   int a = something;
  }
}
```

Whether 'a' is part of the class or part of the constructor will be broken if the language protocol's end doesn't encompass the entire structure.

Also if you think about the semantics __init__ is just the name. It's telling us there's a function. The function does not begin and end with the name of the function.

I think the Python language server team should look into this more - I think they're going to run into issues with other LSP editors if they don't get this right.

**Comment by lgeiger** [comment]
> So from what I can tell the Python language server is thinking in terms of symbols rather than constructs? i.e. it doesn't say function init runs from line 1 to 10 and but rather says it runs from the start of the token init until the end.

That's true.

> It doesn't look like the spec is particularly clear here but doing that can easily lead to confusing cases in many languages.

I see that this can lead to confusion. What about not checking the end position if start and end position are on the the same line? I imagine there are multiple language servers thinking in terms of symbols rather than constructs.

> I think the Python language server team should look into this more - I think they're going to run into issues with other LSP editors if they don't get this right.

@gatesn Do you think this is possible to change in `pyls` itself?

**Comment by gatesn** [comment]
Absolutely possible to change, and very open to having this produce a document structure vs flat symbols.

Obviously the goal here is to have all languages behave the same way.

**Comment by gatesn** [comment]
My concern is that the protocol explicitly warns against this behaviour: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#document-symbols-request

> The document symbol request is sent from the client to the server to return a flat list of all symbols found in a given text document. Neither the document's location range nor the documents container name should be used to reinfer a hierarchy.

**Comment by gatesn** [comment]
Which might explain why this ticket has been open for so long: https://github.com/Microsoft/vscode/issues/5605

**Comment by damieng** [comment]
It doesn't explain why you can't infer a hierarchy from this information.

Our implementation is based on v2 of this API which includes no such disclaimer https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md

**Comment by damieng** [comment]
@gatesn Any progress on the pyls front here?  If not we'll have to figure out some kind of workaround client side.

**Comment by lgeiger** [comment]
@damieng Thanks for pinging. I'll investigate if it's possible. I know Nuclide does something similar, maybe we can use it for inspiration.

**Comment by lgeiger** [comment]
Thanks for the great feedback, I opened https://github.com/palantir/python-language-server/pull/175 to fix this.
