### ISSUE TITLE
initialize does not pass rootUri used by LSP 3.0

### ISSUE THREAD

**Issue by ajoberstar** [atom/atom-languageclient#124]
According to [Language Server Protocol 3.0](https://github.com/Microsoft/language-server-protocol/blob/3.0.0/protocol.md#initialize) InitializeParams contains both a `rootPath` (though deprecated) and `rootUri` (preferred). Both of these are supported [in LSP4J](https://github.com/eclipse/lsp4j/blob/3c309e0fe63056bb8146c104774c0ebb2112cb58/org.eclipse.lsp4j/src/main/xtend-gen/org/eclipse/lsp4j/InitializeParams.java#L77).

See [InitializeParams type definition](https://github.com/atom/atom-languageclient/blob/e37fc73eeb956adb8c4e1b911e7d21f29f55ea76/lib/languageclient.js#L358) for lack of `rootUri` and [getInitializeParams method](https://github.com/atom/atom-languageclient/blob/v0.6.4/lib/auto-languageclient.js#L78) for lack of providing it in the call.

Visual Studio Code passes both (as seen in their [InitializeParams type](https://github.com/Microsoft/vscode-languageserver-node/blob/92b157107b3284a6fdae2c3863707e4b39f315e9/protocol/src/protocol.ts#L671) and their [initialize method](https://github.com/Microsoft/vscode-languageserver-node/blob/42a04f600f2d023ef2ba81002f4235e22e5a54fe/client/src/client.ts#L2497).

This presents as an issue in Atom where ide-java, relying on eclipse.jdt.ls, sends initialize calls with a `rootPath` only, which currently JDT ignores (only reading the `rootUri`). As a result, support for build tools that configure the classpath (Maven and Gradle) doesn't work. I'm opening a ticket with eclipse.jdt.ls to have them check both `rootPath` and `rootUri`, but it would be good for atom-languageclient to support the 3.0 LSP spec (like vscode).

See atom/ide-java#37 for resulting error.

**Comment by damieng** [comment]
Not supporting v3 was intentional at this time but given that we're broken on ide-java because they broke 2.0 compatibility I've added just the rootUri initialization parameter in 0041e5a732f7eac7b6cbe8c13c4407aa76fa9440

ide-java 0.6.6 contains the fix.

Thank you so much for your help in diagnosing this issue.

**Comment by ajoberstar** [comment]
Thanks for the quick response and fix! Just tested it and my Gradle projects are working now.
