### ISSUE TITLE
didChangeWatchedFiles never-ending recursion when a server process writes build artifacts to a subdirectory

### ISSUE THREAD

**Issue by parasyte** [atom/atom-languageclient#125]
This was originally reported against `ide-rust`: https://github.com/mehcode/atom-ide-rust/issues/9 The language server `rls` writes build artifacts to a subdirectory of the atom project. `atom-languageclient` has a FS watch on the project directory to trigger the client's language server. In this particular case, the language server is triggers the FS watch, which causes an infinite loop of file changes.

The easiest solution I can imagine here is to ignore all changes in file paths matching `.gitignore`. It would solve this specific manifestation of the bug, and provide an escape hatch for similar clients if they hit the problem in the future.

FWIW there is a simple workaround patch provided in [this comment](https://github.com/mehcode/atom-ide-rust/issues/9#issuecomment-338647456) which hardcodes the `rls` artifact directory.

**Comment by damieng** [comment]
We could add an ignore for .gitignore entries but that would involve taking a dependency on a wildcard matching library and filtering for every single entry.

Really language servers themselves should not be treating didChangeWatchedFiles as an instruction to rebuild all when it is intended just to be a file notification.

**Comment by alexheretic** [comment]
It could be nice to allow clients to implement their own filtering in addition to any server filtering. This could be done with a extendible method on `AutoLanguageClient`.

```javascript
class AutoLanguageClient {
  /**
   * `didChangeWatchedFiles` message filtering, override for custom logic.
   * @param {string} filePath path of a file that has changed in the project path
   * @return {boolean} false => message will not be sent to the server
   */
  filterChangeWatchedFiles(filePath) {
    return true;
  }
  ...
}
```
That function can be overridden by clients providing client specific filtering, and passed to (and called within) `ServerManager` instances.

```javascript
class ServerManager {
  projectFilesChanged(fileEvents) {
    ...
      for (const fileEvent of fileEvents) {
        if (this._changeWatchedFileFilter(fileEvent.path) === false) {
          continue
        }
    ...
  }
  ...
}
```
This way clients not interested in filtering are unaffected. I can raise a PR if this seems workable?

**Comment by Arcanemagus** [comment]
It would be much better if the language servers handled this themselves, after all the _entire_ point of them is to consolidate the work of implementing things like that in a single place for everyone that uses them.

**Comment by alexheretic** [comment]
Sure, in fact I've submitted a PR to improve this Rls-side. However, as apparently not all language clients behave this way it seems a reasonable power for a client implementation to have, particularly for language that may expect a lot of generated files in the project directory.

**Comment by damieng** [comment]
I think this would be a reasonable compromise and would accept a PR.

**Comment by damieng** [comment]
Will go out in next version shortly.
