### ISSUE TITLE
Language server erroneously stopped when "soft" opening new file 

### ISSUE THREAD

**Issue by hansec** [atom/atom-languageclient#126]
If a single source file is opened by "soft" opening the file through a single click and a different file is selected/opened the language server is erroneously stopped and not restarted for the new file. I am using "soft" opening to describe when selecting a new file replaces the current tab instead of opening in a new tab. This behavior occurs with at least a few different language servers including [ide-typescript](https://github.com/atom/ide-typescript) and [ide-csharp](https://github.com/atom/ide-csharp) based on this package.

In the attached example "main.js" is opened first and an outline is generated as expected. Then when the editor is switched to "main2.js" (the two files are identical) an outline is not generated. The debug console shows that the server is closed and not restarted for the new file. 

![server_stop_ex](https://user-images.githubusercontent.com/821577/31952622-b149acba-b8a6-11e7-91b9-5c0bb4db8563.gif)

**Comment by hansec** [comment]
It appears this has fixed itself for me as well. All the language servers I have installed now work as expected when switching files. Maybe the most recent Atom version (1.22.0) fixed this, I definitely remember still seeing the issue earlier this week before I updated and I think that was the only relevant update I installed this week.

For reference I am using MacOS 10.12.6.

**Comment by alexheretic** [comment]
Its the same story for me, an issue on _1.21.2_ but no longer reproducible on _1.22_.
