### ISSUE TITLE
Add ide-haskell-hie to community packages

### ISSUE THREAD

**Issue by Tehnix** [atom/atom-languageclient#131]
I wanted to hear if we could add [ide-haskell-hie](https://github.com/Tehnix/ide-haskell-hie) to the [community packages](https://github.com/atom/atom-languageclient/wiki/List-of-Atom-packages-using-Atom-LanguageClient) wiki entry.

You can copy the markdown below directly,

```
[ide-haskell-hie](https://github.com/Tehnix/ide-haskell-hie) provides Haskell support via the [Haskell IDE Engine](https://github.com/haskell/haskell-ide-engine)
```

**Comment by damieng** [comment]
Done! Thanks.
