### ISSUE TITLE
Restarting the client programmatically 

### ISSUE THREAD

**Issue by alexheretic** [atom/atom-languageclient#135]
Hi, I'm trying to deactivate the client and reactivate in order to handle config changes. However, it sort of works but doesn't seem to cleanup up properly. Doing it a few times leads to a whole bunch of errors.
```js
// reactivate
this.deactivate().then(() => this.activate())
```
Is there a working/correct way to do this?

**Comment by damieng** [comment]
There's no way to do this just yet but we're hoping to get to it this in the next week or so, being tracked at #71

**Comment by damieng** [comment]
Just re-read this - you want to shut down the entire package and restart it?  I don't think we'll want that to be the way we handle config changes.

You can listen to config changes and then restart the language server once #71 is done. Are there any other paths/scenarios that wouldn't cover for you?

**Comment by alexheretic** [comment]
In this case it's config controlling the version of the language server (rls) itself. When changed I want to shutdown all servers and restart them with the new config.

**Comment by damieng** [comment]
I think #71 will have you covered. Restarting the package itself will probably have all sorts of issues about not restarting, won't kill servers that didn't respond in a reasonable amount of time etc.

**Comment by alexheretic** [comment]
Ok thanks @damieng, I'll give it a try when its out!

**Comment by nathansobo** [comment]
Looking forward to this as well. The use case is for switching between variants of the same language server, such as nightly, beta, stable etc.
