### ISSUE TITLE
textDocument/willSave, willSaveWaitUntil, and didSave

### ISSUE THREAD

**Issue by daviwil** [atom/atom-languageclient#138]
We can use [`TextBuffer.onWillSave`](https://atom.io/docs/api/v1.22.0/TextBuffer#instance-onWillSave) and [`TextBuffer.onDidSave`](https://atom.io/docs/api/v1.22.0/TextBuffer#instance-onDidSave) to get these working.  Will require keeping an eye on any TextBuffers which are relevant to the language server.

**Comment by damieng** [comment]
The code to track which editors is at https://github.com/atom/atom-languageclient/blob/master/lib/adapters/document-sync-adapter.js and currently handles the didSave and didOpen etc.

**Comment by daviwil** [comment]
Awesome, thanks!

**Comment by damieng** [comment]
This was done in the v3 work right?

**Comment by rictic** [comment]
willSaveWaitUntil isn't in yet it seems.

**Comment by daviwil** [comment]
That one may require a change in Atom APIs to delay the save until subscribers have a chance to perform last-minute edits. I'll look into that today!

**Comment by rictic** [comment]
Awesome! It'll let us implement one of my all time favorite features, fix warnings on save.

**Comment by Arcanemagus** [comment]
@daviwil Isn't this already supported through `TextBuffer::onWillSave`?

**Comment by daviwil** [comment]
@Arcanemagus Wow, how did I miss that?  Thanks a lot!

**Comment by Arcanemagus** [comment]
It's one of those functions that is _only_ on `TextBuffer` and not aliased in `TextEditor`, so if you don't think to go through to that to look for it, it's easy to miss 😉.

**Comment by daviwil** [comment]
I actually did use onWillSave [here](https://github.com/atom/atom-languageclient/blob/master/lib/adapters/document-sync-adapter.js#L164) but somehow I missed the callback parameter...  Probably didn't have enough coffee at that moment :)

**Comment by damieng** [comment]
Will continue to track this on #176
