### ISSUE TITLE
Allow context menu to send cursor position

### ISSUE THREAD

**Issue by damieng** [atom/atom-languageclient#14]
Right now Atom does not record or send the position of where the context menu was created and so the LSP relies on the cursor position when Go To Definition is activated from that menu (and potentially Rename Symbol in the future)

Atom should additionally send the nearest line and character position with the message so that it can be utilized in such calls.

**Comment by hansonw** [comment]
We have adopted a simple but less-than-ideal Hack in Nuclide to work around this - record the mouse event during the creation hook :D https://github.com/facebook/nuclide/blob/master/pkg/nuclide-refactorizer/lib/main.js#L113

This is a really common pattern, though, so we should probably work on an Atom PR for this.

**Comment by damieng** [comment]
"Go To Definition" is actually part of symbols view. Control-click does it's own thing so we don't need this right now.
