### ISSUE TITLE
Not receiving textDocument/publishDiagnostics requests

### ISSUE THREAD

**Issue by kwerle** [atom/atom-languageclient#143]
I'm sure this is some problem with my server or the wiring to it, but I'd sure appreciate a hand.

I'm working on ide-ruby, and I'm not receiving textDocument/publishDiagnostics requests - though I thought I'd configured my package.json correctly.

So I think this is an off topic request in that I assume things are working on your end - but I'd sure like for someone to take a look.

https://github.com/kwerle/ide-ruby/issues/4

TIA,
Kurt

**Comment by damieng** [comment]
Hmm, you have the linter service declared in the package.json which is pretty much all you need to do.

Have you tried switching on the debugging with `atom.config.set('core.debugLSP', true)` to see if the messages are coming through at all?  (output is into the dev tools window and you will need to restart atom or at least the language server)

**Comment by kwerle** [comment]
Yeah, you can see in https://github.com/kwerle/ide-ruby/blob/develop/src/main.js that I have it enabled - so I can see that call being sent to the TypeScript server, but not to the ruby server.

So I was thinking maybe there something about the formatting of my package.json file that's broken - but I just can't figure it out.

```
Ruby (Ruby-lang-server) Server starting "/Users/kurt/Source/ide-ruby/"
logger.js:33 Ruby (Ruby-lang-server) starting "/usr/local/bin/docker run --rm -i local_ruby_language_server"
logger.js:33 TypeScript (SourceGraph) Server starting "/Users/kurt/Source/ide-ruby/"
logger.js:33 TypeScript (SourceGraph) starting child Node "node_modules/javascript-typescript-langserver/lib/language-server-stdio"
logger.js:33 Ruby (Ruby-lang-server) rpc.sendRequest initialize sending Object {processId: 69199, capabilities: Object, rootPath: "/Users/kurt/Source/ide-ruby/", rootUri: "file:///Users/kurt/Source/ide-ruby/"}
logger.js:33 TypeScript (SourceGraph) rpc.sendRequest initialize sending Object {processId: 69200, capabilities: Object, rootPath: "/Users/kurt/Source/ide-ruby/", rootUri: "file:///Users/kurt/Source/ide-ruby/"}
internal/process/next_tick.js:67 GET atom://nuclide/modules/nuclide-commons-ui/styles/nuclicons.ttf net::ERR_FILE_NOT_FOUND
module.exports.TreeView.isVisible @ <embedded>:120767
module.exports.TreeView.onStylesheetsChanged @ <embedded>:120572
(anonymous) @ <embedded>:119189
(anonymous) @ <embedded>:119271
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
logger.js:33 Ruby (Ruby-lang-server) rpc.sendRequest initialize received (1102ms) Object {capabilities: Object}
logger.js:33 TypeScript (SourceGraph) rpc.sendRequest initialize received (1097ms) Object {capabilities: Object}
logger.js:33 Ruby (Ruby-lang-server) rpc.sendNotification textDocument/didOpen Object {textDocument: Object}textDocument: ObjectlanguageId: "ruby"text: "# This file is used for testing the atom integration.↵# Feel free to ignore it.↵require 'csv'↵↵class Foo↵↵  def bar↵    puts "bar"↵  end↵↵  def baz↵    this.bar↵    this.ba↵  end↵end↵↵class Bar↵↵  def bing↵    Foo.new.b↵↵  end↵↵end↵"uri: "file:///Users/kurt/Source/ide-ruby/test.rb"version: 1__proto__: Object__proto__: Object
logger.js:33 TypeScript (SourceGraph) rpc.sendNotification textDocument/didOpen Object {textDocument: Object}
logger.js:33 TypeScript (SourceGraph) rpc.sendNotification textDocument/didOpen Object {textDocument: Object}
logger.js:33 TypeScript (SourceGraph) rpc.sendNotification textDocument/didOpen Object {textDocument: Object}
logger.js:33 Ruby (Ruby-lang-server) Server started "/Users/kurt/Source/ide-ruby/" (pid 69199)
logger.js:33 TypeScript (SourceGraph) Server started "/Users/kurt/Source/ide-ruby/" (pid 69200)
logger.js:33 Ruby (Ruby-lang-server) rpc.sendRequest textDocument/documentSymbol sending Object {textDocument: Object}
logger.js:33 TypeScript (SourceGraph) rpc.onNotification ["window/logMessage", Object]0: "window/logMessage"1: Objectmessage: "Found package file:///Users/kurt/Source/ide-ruby/package.json"type: 4__proto__: Objectlength: 2__proto__: Array[0]
logger.js:33 Ruby (Ruby-lang-server) rpc.sendRequest textDocument/documentSymbol received (29ms) [Object, Object, Object, Object, Object]
logger.js:33 TypeScript (SourceGraph) rpc.onNotification textDocument/publishDiagnostics Object {uri: "file:///Users/kurt/Source/ide-ruby/src/help_cmd.js", diagnostics: Array[0]}
logger.js:33 TypeScript (SourceGraph) rpc.onNotification textDocument/publishDiagnostics Object {uri: "file:///Users/kurt/Source/ide-ruby/src/welcome_notification.js", diagnostics: Array[0]}
logger.js:33 TypeScript (SourceGraph) rpc.onNotification textDocument/publishDiagnostics Object {uri: "file:///Users/kurt/Source/ide-ruby/src/main.js", diagnostics: Array[0]}
logger.js:33 Ruby (Ruby-lang-server) rpc.sendNotification textDocument/didChange Object {textDocument: Object, contentChanges: Array[1]}
```

**Comment by damieng** [comment]
So textDocument/publishDiagnostics is not actually a request you'll see.  It's something you as a language server send to the client when you have diagnostics to display on the screen.

Traditionally I've seen two triggers on the language server people have used to decide if to parse the code and send publishDiagnostics. The first is after initialize and the second is onDidOpen.  Your preference probably depends on performance and/or expectations of the language author.

I'd start with onDidOpen.  You probably want to then re-evaluate the contents and re-send the results after onDidChange with some amount of time to de-bounce such requests (e.g. 1 second).

**Comment by kwerle** [comment]
Thanks - that makes a whole lot of sense.  So it is reasonable to return diagnostics from open or change.  That isn't at all clear from https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_didOpen.
Are there any other messages that could/should be returned that way?  I guess showMessage and logMessage?

Thanks again - super helpful.  I bestow upon you one internet point!

**Comment by kwerle** [comment]
I've started to get this working.
Thanks again!
https://github.com/kwerle/ruby_language_server/issues/7
