### ISSUE TITLE
Please provide a generic language server plugin built on top of this library to load up any choice of binary as language server

### ISSUE THREAD

**Issue by JonasT** [atom/atom-languageclient#15]
Please provide a generic language server plugin built on top of this library to load up any choice of binary as language server, with a UI that is as simple as possible (e.g. which allows to specify any language server binary which the user already has somewhere installed on disk unrelated to the Atom editor install, and the absolute minimal other information required to use it like for example the file extensions to use this language server binary for).

This would easily allow plugging in language servers that don't have native plugins for Atom yet to use them until an official plugin for that language is available.

**Comment by damieng** [comment]
It is actually incredibly easy to create a language server package - it's basically a case of filling in 3 fields and a command line unless you're package does anything more advanced (such as requiring platform-specific fields, downloading binaries or wiring up extensions)

I'd rather we spend our time helping getting packages up and available for people to use - I fear if we were to go down the generic route we'd be constantly fielding requests to extend it to handle such scenarios above as well as having to field questions about manual configuration problems.
