### ISSUE TITLE
Trouble getting server process to start

### ISSUE THREAD

**Issue by cfinegan** [atom/atom-languageclient#156]
I'm working on an IDE integration for Racket, and I'm having some trouble getting the language server recognized by the Atom client. This is my first Atom plugin so I'm sure it's some configuration issue on my end. 

When I switch to a `.rkt` file, it seems that `startServerProcess` is not firing correctly. I've looked into issue #107 regarding `startServerProcess` and I've followed the troubleshooting steps laid out in that post.

- I have `source.rkt` registered in both the `package.json` and `getGrammarScopes` of my IDE plugin. 
- I've created a (barebones) grammar plugin for Racket, which is being detected correctly when I switch to a `.rkt` file. 

I've also cloned yang-lsp and ide-yang from issue #107 and can't get *his* language server to load correctly either. When I load a `.yang` file, I get the correct syntax highlighting from the yang grammar, but the server is not invoked at all.

The furthest I've gotten in my troubleshooting is to try overwriting `shouldStartForEditor` to always return `true`, which forces the language server to load (as expected), but comes with other issues: When I override this method in the ide-yang, it simply crashes. The Racket langserver will start under these conditions (and I can see its process with `ps --forest`), but doesn't seem to be correctly reporting its output to the client. I can see its `stderr` if I redirect it to a file, but the Atom client does not seem to register any of the diagnostic messages that get sent over the wire. 

Any tips for further troubleshooting would be greatly appreciated.

Here are the links to my code:
[atom-ide-racket](https://github.com/cfinegan/atom-ide-racket)
[atom-language-racket](https://github.com/cfinegan/atom-language-racket)
[racket-langserver](https://github.com/jeapostrophe/racket-langserver)

**Comment by daviwil** [comment]
Hi @cfinegan, I apologize for not responding to this sooner.  Looks like you figured out the issue based on a [recent commit](https://github.com/cfinegan/atom-ide-racket/commit/124113e37e6eae2a191fca9cabd9e6df0dd67c94) I found on atom-ide-racket?  Thanks for sticking with it!

**Comment by cfinegan** [comment]
Yes, that turned out to be the issue preventing the server from starting for `.rkt` files. Adding `source.racket` as a grammar scope for Racket fixed it.
