### ISSUE TITLE
"Ignored Names" settings not respected

### ISSUE THREAD

**Issue by mgrip** [atom/atom-languageclient#159]
I originally posted this under ide-php: https://github.com/atom/ide-php/issues/85 - but I _think_ it would actually be implemented at the atom-languageclient level?

Anyways, it doesn't seem that files matching the atom "Ignored Names" setting are actually ignored by any of the language servers. This causes performance problems for larger projects, especially ones including 3rd party libraries.

**Comment by damieng** [comment]
The problem is there is no way for Atom to tell the language server to ignore certain files or folders - it's simply not part of the spec.

**Comment by mgrip** [comment]
Thanks for the input @damieng - in that case ide-php is pretty much unusable for me because of performance issues. I know that there's probably not much to be done on the client side of things since it seems most of the responsibility is on the server, but is it just a given that this is not a good solution for large projects? (2.68 GB, 77,708 files is what im dealing with). Would be anxious to hear if there are any performance-related initiatives planned going forward, when I've used this for smaller projects its quite impressive and useful!

**Comment by laughedelic** [comment]
@mgrip I think this is a general problem which is just not addressed yet in the LSP itself. Try searching https://github.com/Microsoft/language-server-protocol/issues for this topic and if there is no open issue yet, you can propose a change (it could be even a non-breaking addition) to the LSP spec. For example, to add workpace source-directories parameter to the initialization request.

**Comment by mgrip** [comment]
For visibility: https://github.com/Microsoft/language-server-protocol/issues/354

**Comment by damieng** [comment]
I think individual language servers need to handle which files and folders they deal with in their own way. If any language package author wants to also bring in the Atom ignored files list they can do that from their ide-x package today by way of either a custom message or additional payload on the initialization parameter.
