### ISSUE TITLE
Filter complete CompletionItems

### ISSUE THREAD

**Issue by rictic** [atom/atom-languageclient#164]
Previously: https://github.com/atom/atom-languageclient/issues/150 #41 #128

It looks like #128 was reverted, but the plan is still to implement client-side filtering. It's helpful for clients to have an issue to follow, so we know when we can switch to client-side filtering for atom users.

**Comment by damieng** [comment]
It's in https://github.com/atom/atom-languageclient/pull/163

Should be merged in the next 24 hours.

**Comment by damieng** [comment]
Fixed in a6a620694b49fe1c2cd51a7d9b698c505ea08416
