### ISSUE TITLE
Add ide-docker to the wiki page

### ISSUE THREAD

**Issue by rcjsuen** [atom/atom-languageclient#168]
Could someone please add the [ide-docker](https://atom.io/packages/ide-docker) package created by @josa42 to the list on the wiki page? Thanks!

**Comment by daviwil** [comment]
@damieng beat me to it ;)

**Comment by damieng** [comment]
Added to https://github.com/atom/atom-languageclient/wiki/List-of-Atom-packages-using-Atom-LanguageClient
