### ISSUE TITLE
Add support for willSaveWaitUntil request

### ISSUE THREAD

**Issue by laughedelic** [atom/atom-languageclient#176]
I see that it's not supported at the moment:

https://github.com/atom/atom-languageclient/blob/e0b9aeb7b8b61538e004c680b16ddc7384c98301/lib/auto-languageclient.js#L115

[`textDocument/willSaveWaitUntil`](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#willsavewaituntiltextdocument-request-leftwards_arrow_with_hook) request is useful for example to run formatting before the document is saved.

**Comment by laughedelic** [comment]
Sorry, I see that it has been mentioned in #138. Feel free to close it. By the way, does it make sense to contribute anything at the moment or it's better to wait until #175 gets merged?

**Comment by damieng** [comment]
It shouldn't matter either way. The TypeScript conversion will be wrapped up this week but we can retroactively convert any new work on top of it.
