### ISSUE TITLE
Switch to `protected` `AutoLanguageClient#startExclusiveAdapters(server: ActiveServer)`

### ISSUE THREAD

**Issue by BoykoAlex** [atom/atom-languageclient#189]
Can we switch `AutoLanguageClient#startExclusiveAdapters(server: ActiveServer)` to `protected`?
I overrode it in JS code to attach adapters for custom messages outside the LSP protocol... The method is `private` in TS, can't override it...

**Comment by damieng** [comment]
We have a specific hook for that called `postInitialization` that is protected and also has an ActiveServer parameter.  

That is how we hook up custom messages in ide-java etc.  Does that work for your use case?

**Comment by BoykoAlex** [comment]
I think it should. I'll try it out.

**Comment by damieng** [comment]
Cool. Let me know if it doesn't and I'll see if we can further tweak the hooks :)
