### ISSUE TITLE
DownloadFile is not able to use content-length header

### ISSUE THREAD

**Issue by henryju** [atom/atom-languageclient#190]
[Contrary to the documentation](https://github.com/atom/atom-languageclient/blob/500af60e80461669354738d14699ae5591f86d25/lib/download-file.ts#L9), it seems you are always forced to manually pass the file length. The code trying to read the Content-Length header is not working. My little understanding (and after lot of debugging) is that fetch is doing a "cors" mode request, and Content-Length is not whitelisted in this mode.

**Comment by damieng** [comment]
Yes, it looks like the server needs to send an extra header to enable this;

`Access-Control-Expose-Headers "content-length"`

I'll add that to the docs - I don't see a way to avoid it unfortunately.
