### ISSUE TITLE
Has there been API changes since 0.7.2?

### ISSUE THREAD

**Issue by Tehnix** [atom/atom-languageclient#195]
For some strange reason, [ide-haskell-hie](https://github.com/Tehnix/ide-haskell-hie) no longer starts on launch, even though nothing was really changed, except bumping the dependencies on `atom-langaugeclient` on the way.

I've tried comparing [ide-haskell-hie.js](https://github.com/Tehnix/ide-haskell-hie/blob/master/lib/ide-haskell-hie.js) and [package.json](https://github.com/Tehnix/ide-haskell-hie/blob/master/package.json) with other LSP clients, but cannot seem to figure out what might be causing it not to launch at all on Haskell files.

I've added a restart command in the package, which does start the LSP server fully, so the server and initialisation itself works, it just never initiates when opening a project.

Was hoping to solicit some help here, if possible :)

**Comment by damieng** [comment]
Are you using the experimental tree-sitter option in Atom?

**Comment by Tehnix** [comment]
Not that I'm aware of, no. I haven't actively set anything, but would there be a way to double check?

**Comment by Tehnix** [comment]
Jesus christ, it was me being stupid. I [had used `activationCommands`](https://github.com/Tehnix/ide-haskell-hie/blob/6b40c25244b243b315a095f1cd7d5d87fba56903/package.json#L12) to register my restart command, when that was not what you do at all...

Issue is resolved, sorry for taking your time!
