### ISSUE TITLE
window/showMessageRequest notification has no action buttons

### ISSUE THREAD

**Issue by JakeBecker** [atom/atom-languageclient#196]
Tested using the latest release of `atom-languageclient` along with either `atom-ide-ui` or `nuclide`. The Elixir language server sends a request like this:
<img width="391" alt="screen shot 2018-03-14 at 11 41 42 am" src="https://user-images.githubusercontent.com/547940/37424140-ffe745cc-277c-11e8-9664-2845b822895e.png">

And the notification looks like this:
<img width="476" alt="screen shot 2018-03-14 at 11 34 05 am" src="https://user-images.githubusercontent.com/547940/37424160-11300aee-277d-11e8-9610-a1e04aaf9d01.png">

There's no action buttons for the user to click. The same server and request works in in VS Code, suggesting this is a problem with the Atom LSP client.

**Comment by damieng** [comment]
Are there some steps I can take with the elixir package to test this before I upload my fix?  I don't have anything to hand that triggers this message.

**Comment by JakeBecker** [comment]
Sure, install Elixir on your system and then `apm install ide-elixir`. Clone this repo, and you should get a request either on start or any time you save a file: https://github.com/JakeBecker/show_message_request

**Comment by JakeBecker** [comment]
If you want, you can push your fix to a branch and I'll test it locally.

**Comment by damieng** [comment]
It's now up in `fix-showMessageRequest-buttons` branch

**Comment by JakeBecker** [comment]
Aah, I may be unable to test this for you. In `ide-elixir`, I did `npm install --save atom/atom-languageclient#fix-showMessageRequest-buttons` and `apm link`, but now I get this error when launching:

<img width="480" alt="screen shot 2018-03-14 at 12 22 06 pm" src="https://user-images.githubusercontent.com/547940/37425958-6bc075e8-2782-11e8-8684-23fddd6ab982.png">

Likely a problem on my end, but may be easier for you to test it yourself than for me to figure this out.

**Comment by damieng** [comment]
go into wherever you checked out atom-languageclient and type `npm i` then `npm link .`  then go into your ide-elixir package and type `npm link atom-languageclient`

Once you're done testing you can just `npm unlink atom-languageclient` from your ide-elixir package.

I'll can also test this afternoon.

**Comment by JakeBecker** [comment]
Cool, that appears to have fixed it. 👍

**Comment by damieng** [comment]
I'll get this merged in and a new version out today.
