### ISSUE TITLE
Connecting to a container

### ISSUE THREAD

**Issue by bhack** [atom/atom-languageclient#199]
Could be possible to support language servers that run in containers?
Often many dependencies are installed directly inside the dev container also if ide is still running on the host.
See
https://github.com/lgeiger/ide-python/issues/48

**Comment by damieng** [comment]
Nothing in atom-languageclient should stop that - ide authors can specify what commands to run to start the container so it could easily be a docker command - and atom-languageclient is also happy to connect over tcp/ip sockets.

I don't however think we'd want to bake anything docker-specific into atom-languageclient - it would be up to authors to implement that.
