### ISSUE TITLE
Support for Rust Language Server

### ISSUE THREAD

**Issue by amand1996** [atom/atom-languageclient#2]
I wish to make an integration of atom-languageclient with Rust Language Server (https://github.com/rust-lang-nursery/rls). Is this repository supporting it currently? How to proceed using this? Any documentation?

**Comment by damieng** [comment]
Hi. This repo is currently experimental but you can see some examples of how to use it at https://github.com/atom/languageserver-java and https://github.com/atom/languageserver-csharp
