### ISSUE TITLE
atom-languageclient fails on hacked up JSON it tried to send itself(?)

### ISSUE THREAD

**Issue by JonasT** [atom/atom-languageclient#20]
I get a JSON parse error "Uncaught SyntaxError: Unexpected end of JSON input" at `/home/jonas/.atom/packages/language-tethercode/node_modules/atom-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:202`. Full backtrace:
```
at StreamMessageReader.onData (/home/jonas/.atom/packages/language-tethercode/node_modules/atom-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:202:23)
    at Socket.<anonymous> (/home/jonas/.atom/packages/language-tethercode/node_modules/atom-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:166:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```
I modified that line of code where the error occurs to output the JSON that fails to parse there, and I get this output (yes, it's cut off at the end):
```

{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":13592,"capabilities":{},"rootPath":"/home/jonas/Develop/tethercode-language-serve
```

I tested this with a binary that just eats stdin and never outputs anything ever as a language server. Obviously, as a result this message cannot be generated by anything except atom-languageclient itself. Therefore, I think this might be a bug?

Edit: dunno if relevant, but I was using this incredibly simple plugin code that is almost unmodified from the README.md to run atom-languageclient when hitting this issue: https://gitlab.com/tethercode/atom-language-plugin/blob/53c84ff2554807b3d3749c3331e867accb5664c5/lib/main.js

**Comment by damieng** [comment]
By default language servers use stdout and stdin to communicate.  If your server is using console.log to write out what it gets that will be be sent back to atom-languageclient and could easily cause this error.

If you're using the vscode-languageserver library to manage the connection you can wire up console.log and console.error to instead send back log and error messages over json-rpc which will show in the console.log in Atom by adding two lines after your createConnection, e.g.

```javascript
const connection = createConnection()
console.log = connection.console.log.bind(connection.console)
console.error = connection.console.error.bind(connection.console)
```

**Comment by JonasT** [comment]
I wrote something from scratch which doesn't output anything - at least it's not supposed to, and in all manual tests it never did.

Interestingly, my log shows I got proper complete JSON-RPC requests from Atom though, so I'm not sure what exactly the atom-languageclient error popup is so confused about..

**Comment by damieng** [comment]
How are you writing your log out?

**Comment by JonasT** [comment]
I'm dumping it into a hardcdoed file path `/tmp/tethercodels-input-dump.log` with regular file I/O for now. I'll change that for the final release of course :stuck_out_tongue: but for some first tests that worked well enough

**Comment by JonasT** [comment]
This is probably also related to me using stdin/stdout wrong as in #24 - since I switched to TCP ports that strange behavior is gone. Since my stdin/stdout use was quite hackish anyway, I'll assume here as well that this was in the end a bug on my side, and since I use TCP now all works fine.
