### ISSUE TITLE
Set a timeout on willSaveWaitUntil request

### ISSUE THREAD

**Issue by laughedelic** [atom/atom-languageclient#200]
See https://github.com/atom/atom-languageclient/pull/193/files/5a9894f84aae9542fc710ca54b6a7e14142fea04#r176509321

From the [LSP spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_willSaveWaitUntil):

> Please note that clients might drop results if computing the text edits took too long or if a server constantly fails on this request. This is done to keep the save fast and reliable.

**Comment by damieng** [comment]
Do you want to have a crack at this before we put a new version out or just go with a new version?

**Comment by laughedelic** [comment]
I had some code for this, but I wasn't sure I'm doing it right, so I just left it out of #193. I'll just open a PR and you tell me if it's worth working on or better to leave it for later (for somebody more prepared).

**Comment by laughedelic** [comment]
I see that you already tagged v0.9.5 👍 So I can already start using it. I think it's better to have frequent releases and this particular thing is not critical to block it.

**Comment by laughedelic** [comment]
Fixed in #203
