### ISSUE TITLE
Autocomplete Adapter has too aggressive caching

### ISSUE THREAD

**Issue by edjubuh** [atom/atom-languageclient#201]
I think the rules for caching the last autocomplete session are a bit funky. If I type "read" and then go back to the start of the line and start trying to type "printf", I don't get any relevant suggestions for printf.

I know the issue has to do with deciding when the last cached autocomplete request [is invalid](https://github.com/atom/atom-languageclient/blob/master/lib/adapters/autocomplete-adapter.ts#L83) - the logic has to do with where the cursor position was and doesn't take into account what was typed. A request to the server is sent once "rea" is typed (if 3 characters are needed to trigger autocomplete), but never again once you hit backspace and get the line to "pri". I couldn't find anything too clear in the LSP spec on how (if at all) clients should be caching autocomplete sessions.

I'm not sure if we should try to modify the caching logic to also be cognizant of what text the (edited) line had when the request was sent, or if we should also allow the servers to deal with caching and just send the autocomplete requests on every character press.

**Comment by damieng** [comment]
It should definitely reflect updated result - do you have the setting in autocomplete-plus enabled that allows us to hook in to the delete event enabled?

![image](https://user-images.githubusercontent.com/118951/37844897-60d056c0-2e86-11e8-8f4f-1dc269e963dc.png)

**Comment by edjubuh** [comment]
Yes

**Comment by damieng** [comment]
Can you let me know what ide package you were using and a sample of the text so I can try and repro?

**Comment by edjubuh** [comment]
I've been playing around with ide-cquery.

I just found this: https://github.com/cquery-project/cquery/blob/master/src/config.h#L116-L121

I configured that and everything started working as expected, so I'm going to consider this issue resolved. Thanks for keeping me honest about making sure this affects multiple ide packages :)

**Comment by damieng** [comment]
Not a problem at all - the autocomplete caching has been a bit of a minefield so I'd definitely like to hear about any concerns and investigate them :)

**Comment by damieng** [comment]
Do you have `Allow Backspace to Trigger Autocomplete` set as in the screenshot above? (it's in autocomplete-plus settings)

**Comment by nwolverson** [comment]
Yes - but it's not the behaviour on backspace which is the issue, it's after the backspace (when the suggestions disappear) and the next character being typed. Even if that did fix the issue, I wouldn't want to have to impose that preference on users.
