### ISSUE TITLE
didChangeWatchedFiles is broken for files changed outside of the editor

### ISSUE THREAD

**Issue by laughedelic** [atom/atom-languageclient#204]
I noticed that my client is not sending `window/didChangeWatchedFiles` notifications for files in the project that are changed outside of the editor. I see in the code that there are 2 places where this notification is sent:
* `lib/adapters/document-sync-adapter.ts` bound to explicit changes in the open buffer — it works well
* `lib/server-manager.ts` which seems to misbehave:

    https://github.com/atom/atom-languageclient/blob/cbe48b08235c48ae8aa669c9f083c98855bf0c87/lib/server-manager.ts#L311

I don't see any recent changes to this code so I don't know why it stopped working. I would appreciate any clues on how this could be fixed.

**Comment by damieng** [comment]
Is it not hitting that function at all?  Two things that can cause that is a. using an older version of atom that doesn't have the `atom.project.onDidChangeFiles` api or that the file change watcher isn't working properly.  Try adding an atom.project.onDidChangeFiles call to see if it's working for you, e.g.

`atom.project.onDidChangeFiles(console.log)`

Then try changing a file and see if it appears on your devtools console log. If it doesn't then there is a problem with Atom's tracking of your file system which will need to be filed over in atom.

If both of those work fine then it might be the filtering. The default is to let everything through here;

https://github.com/atom/atom-languageclient/blob/0f6bb78d2081e49f1e1a9a5e70b4c6eee89196c1/lib/auto-languageclient.ts#L688

but that can be overridden in your own autolanguageclient subclass in your ide-x package.

**Comment by laughedelic** [comment]
@damieng thanks for the guidance! It took me quite some time to debug the problem and in the end I found `fileSystemWatcher: "atom"` in my config. I guess it was my own fault, probably I changed it after some recent Atom update (although I don't remember it).

Anyway, problem is solved and sorry for suspecting atom-languageclient at first 😅
