### ISSUE TITLE
Include ide-fortran in the community packages list

### ISSUE THREAD

**Issue by hansec** [atom/atom-languageclient#208]
Hello, I have written an [ide package for fortran](https://atom.io/packages/ide-fortran) and an underlying [language server](https://github.com/hansec/fortran-language-server). Both have now reached a stable point and I would like to have them included in the list of community packages if possible for anyone who may be interested. Thanks!

**Comment by damieng** [comment]
Done, thanks!

**Comment by hansec** [comment]
Great, thanks! Although, it looks like my github username snuck into the language server link. Can you update it to just [Fortran language server](https://github.com/hansec/fortran-language-server) when you get a chance? Thanks again.

**Comment by damieng** [comment]
We generally like to name language servers as there might be more than one language server available. If you're totally opposed I can remove it until there's a collision.

**Comment by hansec** [comment]
Ok, sounds good. Can you change it to [hansec's Fortran language server](https://github.com/hansec/fortran-language-server) then to match the naming used for the PHP ide? Thanks!

**Comment by damieng** [comment]
Done.
