### ISSUE TITLE
README.md should link a minimal complete language client example package right below the example code excerpt

### ISSUE THREAD

**Issue by JonasT** [atom/atom-languageclient#21]
Right now, the README.md contains a short snippet which nicely illustrates how to open up a language client for someone familiar with Atom's plugin system.

However, for someone dropping by who isn't deeply familiar with the plugin system yet, it's not very obvious 1. where this code needs to be put in a plugin, 2. that `main` needs to be set in the package.json to make it run, 3. that activation hooks need to be set in the package.json and other stuff. In short, it doesn't nicely show to a newcomer how to create the whole minimal package that actually starts and successfully connects to a language server for a new choice of language.

Therefore, I am suggesting the following change:

The README.md should link a minimal complete language client example package right below the example code excerpt, similar to this:

> ...
> module.exports = new OmnisharpLanguageServer()
>
> To see a minimal implementation of this as a complete package, [http://example.com/fill-in-link-here](look at this minimal example package).
>
> Some more elaborate scenarios can be found in the Java LSP package which includes:
> ...

While linking / mentioning the more elaborate real world examples below helps, they shouldn't replace offering a minimal complete setup showing how to use the library. (IMHO)

**Comment by damieng** [comment]
Right beneath that section is another section called Available packages that links to complete GitHub repos for Atom packages for Java (Eclipse JDT language server) and C# (Omnisharp-node language server)

**Comment by JonasT** [comment]
Yes I am aware, however that was not the point of the ticket.

The point was that real world examples that are usually more complex shouldn't replace the most minimal working example, which I think should be prepared and added as a link as well. It's just a better place to start than a (good) code example which is nevertheless not fully described in where it needs to go and then just sending off the newcomers to real world packages that go beyond illustrating the most basic setup.

It's just a minor nitpick really. Feel free to ignore it too, I just felt like it was a point worth improving when I read the README.md for the first time.

**Comment by damieng** [comment]
Sorry I didn't make it clear - the Omnisharp C# one at https://github.com/atom/languageserver-csharp is *just* the code from the README with the necessary support files to make it an Atom package - i.e. what I thought you were asking for.  There is zero other code.

I agree that many language servers are going to require a lot more additional plumbing (the Java one for example has downloads and platform-specific args) but the Omnisharp one is as minimal as can be.

**Comment by JonasT** [comment]
Ah. Maybe add a note to the README.md then? Since the Java LSP is linked first and obviously has more stuff going on, it's not super obvious that there is also a minimal base example available in one of the later links.

Also, I think it might be helpful for visibility to actually link just this one right below the snippet as a "and here you have this snippet packaged up nicely to run it immediately" kind of thing, and not just in the lower section with the more expanded collection of related packages and other examples.

**Comment by damieng** [comment]
I'll reorder them and clarify it in the readme, thanks.
