### ISSUE TITLE
Include ide-scala in the community packages list

### ISSUE THREAD

**Issue by laughedelic** [atom/atom-languageclient#211]
I'd like to add to the list my package which provides Scala language support using 2 language servers: 

> [Scala](https://github.com/laughedelic/atom-ide-scala) provides Scala language support using [Metals](https://github.com/scalameta/metals) and [Dotty Language Server](http://dotty.epfl.ch/docs/usage/ide-support.html)

```markdown
[Scala](https://github.com/laughedelic/atom-ide-scala) provides Scala language support using [Metals](https://github.com/scalameta/metals) and [Dotty Language Server](http://dotty.epfl.ch/docs/usage/ide-support.html)
```

It's probably confusing why both servers are needed, but the reason is that Metals provides support for Scala 2 and Dotty is a codename for the next version of Scala 3 with builtin LSP, so they are complimentary at the moment.

**Comment by damieng** [comment]
Done!

**Comment by laughedelic** [comment]
Thanks!
