### ISSUE TITLE
Atom editor hang up

### ISSUE THREAD

**Issue by Pavche** [atom/atom-languageclient#216]
Hi.
Since yesterday Atom editor hangs up, not allowing me to continue with programming.
The CPU load increases to 100%.

**Details**
OS: Red Hat Enterprise Linux 7.5.
Atom's version: 1.26.1-0.1
Installed packages: 
1. asciidoc-preview
2. busy-signal
3. intentions
4. language-gherkin
5. linter
6. linter-pylama
7. linter-ui-default
8. xcode-syntax
9. xcode-theme

Please let me know what are the troubleshooting steps.
Thank you in advance.

**Comment by damieng** [comment]
@Pavche I don't think any of the packages you have there use atom-languageclient.

If you are experiencing problems with atom I'd recommend checking out https://github.com/atom/atom repository where it is supported.
