### ISSUE TITLE
multi line select keyboard shortcut gets overridden to wrong key combination in windows

### ISSUE THREAD

**Issue by JoueBien** [atom/atom-languageclient#217]
### Description
While using windows on a mac the hyper click setting for" trigger key" for windows is ignored and uses the OSX command key ( windows key) while using windows. This causes the multiline select shortcut ctrl+click to be changed to windows key+click

### Expected Behavior
multiline select keyboard shortcut should be  should ctrl+click

### Actual Behavior
multiline select keyboard shortcut gets overridden to windows key+click

### Versions
* Atom: 1.26.1
* Client OS: windows running on a macbook pro
* atom-ide-ui: v0.11.2 & v0.11.1

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by damieng** [comment]
I think you meant to file this with atom-ide-ui?  atom-languageclient is just a bridge for language server protocol integration.

**Comment by JoueBien** [comment]
Sorry, the repo link to the atom-ide-ui package in atom seems to have taken me to the wrong repo. Please feel free to close this issue as it is not relevant.
