### ISSUE TITLE
Auto-Complete not working properly

### ISSUE THREAD

**Issue by KJ1010G** [atom/atom-languageclient#222]
Note - I posted this on atom-ide-ui, they told me to post here.
Note - This only started happening after installing atom-ide-ui & ide-java

### Description
When i am typing some code, for example-
frame.setVi
at this point it would correctly show me the auto-complete options.
![issue_java_ide_atom](https://user-images.githubusercontent.com/38991076/41072835-d1553ffa-6a1d-11e8-9cbe-b89a17b835c9.png)
No problems till now.

### Expected Behavior
Now, when I press TAB/ENTER to auto-complete the highlighted option ( setVisible(Boolean b) in this example ) , it should correctly auto-complete in my code.

### Actual Behavior
But it doesn't approximately 70% of time. When i press TAB/ENTER, the options diss-appear.
![issue_java_ide_atom_2](https://user-images.githubusercontent.com/38991076/41073092-384ef27c-6a1f-11e8-9cbe-e11843d381c0.png)
Then i have to press, Ctrl+Space to make the options visible again. And choose the same option( if I choose some other and press TAB, then too nothing happens) again and then press TAB. Then it auto-completes.
Basically, 30% of time, auto-complete works when I press TAB on an option once.
And, 100% of time, auto-complete works when I press TAB on an option twice.
So, 70% (approx) of time i have to press TAB twice.

This is very annoying and slows down coding speed.

Also, this never happens when the option is NOT  of "ide-java" package. The default atom package.
Those options get Auto-completed in first attempt always.

### Versions
* Atom: 1.27.2
* Client OS: Ubuntu 16.04LTS

### Additional Details : Installed packages
- atom-ide-ui 0.12.0
- ide-java 0.8.3 
- and core packages, nothing else

**Comment by UziTech** [comment]
Development of [atom-languageclient](https://www.npmjs.com/package/atom-languageclient) has officially moved to https://github.com/atom-ide-community/atom-languageclient 🎉 

If this is still an issue please consider opening an issue on that repo.
