### ISSUE TITLE
didchange notifications sent multiple times for large file

### ISSUE THREAD

**Issue by lachhebo** [atom/atom-languageclient#224]
Hello, 

I'm using atom 1.27 on fedora 28 with atom-ide-ui, language-ocaml and prettier-atom extensions installed. 

I have written a server for .dk file with full text synchronisation. 
When I'm opening a large .dk file, the didchange notifications is sent many times. The more the file is  large, the more  atom is sending didchange notifications. 

An example :  
- For a 15 lines file. the notification is only sent once. 
- For a 72 lines file. the notification is sent twice. 
- For a 296 lines file, the notification is sent 6 times. 

My package only contain a grammar to identify .dk file and a basic main.js

**Comment by damieng** [comment]
This relies on the built-in atom file system watcher.  I wonder if it's a problem there.

Can you see what File System Watcher you have set in Atom's Core settings.  And see if it reproduces with a different one.  e.g. try "Native operating system APIs" and "Experimental filesystem watching library"
