### ISSUE TITLE
Completion issues at trigger character

### ISSUE THREAD

**Issue by alexheretic** [atom/atom-languageclient#225]
With ide-rust I get incorrect behaviours when completing at the trigger character `::`.

### Example
```rust
struct Foo(u32);

impl Foo {
    fn new(num: u32) -> Foo {
        Foo(num)
    }

    fn new2() -> Foo {
        Foo(123)
    }

    fn new3(num: u32) -> Foo {
        Foo(123 + num)
    }
}

fn main() {
    Foo::┋
}
```
Where `┋` is the cursor.

### Completion from trigger char
Completion with ctrl-space 

Sends _textDocument/completion_:
```js
{ 
  textDocument: { uri: "file:///home/alex/project/rusttmp/src/main.rs" },
  position: { line: 17, character: 9 },
  context: { triggerKind: 1 } 
}
```
And receives:
```js
[{
  label: "new",
  kind: 3,
  detail: "fn new(num: u32) -> Foo",
  insertText: "new(${1:num})",
  insertTextFormat: 2
},{
  label: "new2",
  kind: 3,
  detail: "fn new2() -> Foo",
  insertText: "new2()",
  insertTextFormat: 2
},{
  label: "new3",
  kind: 3,
  detail: "fn new3(num: u32) -> Foo",
  insertText: "new3(${1:num})",
  insertTextFormat: 2
}]
```

However only 2 of the methods are offered as completion options, whereas I would expect all 3. _(The two which are snippets are offerred, while the other is not a snipped)_.
![bad-completion](https://user-images.githubusercontent.com/2331607/42443648-fac3d2a0-8365-11e8-88cb-9b3eb488bdab.png)

Worse when completing with one of these the `::` characters are removed incorrectly.
![after-bad-completion](https://user-images.githubusercontent.com/2331607/42444061-160e494a-8367-11e8-8c5c-a083ece3d20f.png)

### Completion from typed character after trigger char
In the case I type an `n` character to narrow completion ` Foo::n┋` all options are offered and completion does not delete the `::` characters, ie correct behaviour.
![good-completion](https://user-images.githubusercontent.com/2331607/42444166-4d523c9a-8367-11e8-8773-dfb0ca85fc0a.png)

downstream issue: https://github.com/rust-lang-nursery/atom-ide-rust/issues/93

**Comment by damieng** [comment]
Should be resolved by new multi-character completion trigger code in next release.

**Comment by alexheretic** [comment]
Thanks!
