### ISSUE TITLE
CodeAction support appears to be limited to commands

### ISSUE THREAD

**Issue by fredemmott** [atom/atom-languageclient#226]
In master, https://github.com/hhvm/hhast reports edit-based CodeActions (https://github.com/hhvm/hhast/blob/174b96c787d96eb4e9c2ff66666b44c512d10d86/src/Linters/AutoFixingASTLinter.php#L57)

These work correctly in vscode, but do not seem to appear in nuclide with an AutoLanguageClient.

From skimming https://github.com/atom/atom-languageclient/blob/master/lib/adapters/code-action-adapter.ts#L63 , it looks like only command-based CodeActions are supported, not edit-based

**Comment by fredemmott** [comment]
Yep, https://github.com/atom/atom-languageclient/blob/3f8a3ae62281fc89410ff806fe16e03773e5b9f3/lib/languageclient.ts#L329

**Comment by damieng** [comment]
Same as #239 and there is more discussion there, will use that to track.
