### ISSUE TITLE
 textDocument/codeAction

### ISSUE THREAD

**Issue by damieng** [atom/atom-languageclient#23]
Some linters return possibilities for fixing the code. 

We should either expose these through Nuclide diagnostics fixers (recommended) or look at a UI affordance to expose it (that could be-used for Code Actions #11)

**Comment by keplersj** [comment]
This would be pretty crucial for `eslint` and `tslint`

Ref: Microsoft/vscode-eslint#290, Microsoft/vscode-tslint#250

**Comment by hansonw** [comment]
I have a WIP to implement this using the code-actions package in atom-ide-ui - I should have it done today.

@keplersj https://atom.io/packages/linter-eslint works perfectly in the meantime :D
