### ISSUE TITLE
`formatRange` is triggered on save instead of `formatDocument`

### ISSUE THREAD

**Issue by alexfedoseev** [atom/atom-languageclient#230]
https://github.com/atom/atom-languageclient/blob/0f6bb78d2081e49f1e1a9a5e70b4c6eee89196c1/lib/adapters/code-format-adapter.ts#L49-L51

Is there any reason why range formatter is used always for servers that support it?

I noticed pref regression when transitioned `atom-ide-reason` from server that doesn't support range formatting to the one that supports it:

https://github.com/jaredly/reason-language-server/issues/99

I assume `atom-languageclient` should trigger `CodeFormatAdapter.formatRange` via explicit "format-selection" command (I made it up but the point is that it should be triggered explicitly) but on save it should always trigger `CodeFormatAdapter.formatDocument`. Does it make sense?

**Comment by alexfedoseev** [comment]
If I get it right, it supposed to be handled as I proposed but something went wrong.

`atom-ide-ui` handles it?
https://github.com/facebook-atom/atom-ide-ui/blob/cd80d2276e29aba41e296667935a152a6df9dad8/modules/atom-ide-ui/pkg/atom-ide-code-format/lib/CodeFormatManager.js#L243-L244

Not implemented in `atom-languageclient`?
https://github.com/facebook-atom/atom-ide-ui/blob/cd80d2276e29aba41e296667935a152a6df9dad8/modules/atom-ide-ui/pkg/atom-ide-code-format/lib/types.js#L50-L64

**Comment by damieng** [comment]
I think the problem actually lies at 

https://github.com/atom/atom-languageclient/blob/master/lib/auto-languageclient.ts#L613

Here we're only supporting RangeCodeFormatProvider. This would need to be extended to support the document one too https://github.com/facebook-atom/atom-ide-ui/blob/cd80d2276e29aba41e296667935a152a6df9dad8/modules/atom-ide-ui/pkg/atom-ide-code-format/lib/types.js#L54

**Comment by alexfedoseev** [comment]
@damieng I actually went ahead and prepared a PR: https://github.com/atom/atom-languageclient/pull/231
Can you take a look?

**Comment by damieng** [comment]
Looks great, I've gone ahead and merged it.  I'll update the README and get a new version out today.
