### ISSUE TITLE
`didChangeWatchedFiles` on changes in `.git`

### ISSUE THREAD

**Issue by alexfedoseev** [atom/atom-languageclient#232]
I noticed that client sends this to a server:

```
{"jsonrpc":"2.0","method":"workspace/didChangeWatchedFiles","params":{"changes":[{"uri":"file:///Users/Alex/Dev/Projects/path/to/project/.git/FETCH_HEAD","type":2}]}}
```

And a lot of such messages make server feel bad.

I also found this in `CHANGELOG`: https://github.com/atom/atom-languageclient/blob/master/CHANGELOG.md#v066
Not sure if it's regression or unrelated.

**Comment by LaurentTreguier** [comment]
By default, every file change is communicated. Using the `AutoLanguageClient` class, the [`filterChangeWatchedFiles(filePath: string)`](https://github.com/atom/atom-languageclient/blob/master/lib/auto-languageclient.ts#L761) method can be overriden to filter out unnecessary `workspace/didChangeWatchedFiles` notifications.

**Comment by alexfedoseev** [comment]
Thanks! I'll filter it out then.

P.S. Does it makes sense to filter out `.git` by default tho?

**Comment by LaurentTreguier** [comment]
I guess it depends on which files you want to monitor. For example in the server I'm working on I'm only returning `true` for files with a specific name, and the rest is basically filtered out by default.
