### ISSUE TITLE
Hierarchical outline view support?

### ISSUE THREAD

**Issue by isundaylee** [atom/atom-languageclient#235]
The Language Server Protocol has an optional client capability for supporting a hierarchical outline view with multi-level nesting (see the `DocumentSymbol[]` response variant at https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol). Does `atom-languageclient` currently support it? 

If not, I am willing to work on that support if no one else is currently working on it :)

**Comment by damieng** [comment]
Thanks for your enthusiasm in working on this project however this particular feature is already implemented at https://github.com/atom/atom-languageclient/blob/master/lib/adapters/outline-view-adapter.ts

**Comment by isundaylee** [comment]
Hi @damieng, thanks for the pointer! However it seems that the current outline view only supports the *original non-hierarchical outline format*, but not the new hierarchical outline format. In particular, this optional newer outline mode is only enabled when `InitializeParams.capabilities.textDocument.documentSymbol.hierarchicalDocumentSymbolSupport` is set to true.

I think this new `documentSymbol` format was just added this July to the LSP protocol (https://github.com/Microsoft/vscode-languageserver-node/commit/451eee78181d529cfa98ffc7198e2955cdfdc451). It was released as part of `vscode-languageserver-types` version 3.13.0. Currently `atom-languageclient` only depends on `vscode-languageserver-types` version 3.6.1, which makes me think that it only supports the original outline format, not the new one?

**Comment by damieng** [comment]
I see.

We actually generate a hierarchy today using the old format despite the warnings in the LSP not to as it worked out great with a little bit of logic to nest the ranges.

If you want to add support for the new mode please do although we need to also keep compatibility with the old format and continue to generate a hierarchy there too.

**Comment by isundaylee** [comment]
I got an implementation of this working, but it requires bumping `vscode-languageserver-protocol` to at least 3.10.0. I guess this feature alone wouldn't be a good enough reason for bumping the dependency version right? Is there a plan on upgrading `vscode-languageserver-protocol` version some time in the future? If so I can probably wait until that happens before submitting a PR.

**Comment by namibj** [comment]
I've got a fix for the case with ide-cquery. It bypasses the names and relies on the begin/end positions implying a nesting.
Yes, I know it's not referring to upstream, but it works and the code itself seems ok.
It's against 0.9.9 as it is currently in my local packages folder (inside ide-cquery).

``` diff
diff --git a/build/lib/adapters/outline-view-adapter.js b/build/lib/adapters/outline-view-adapter.js
index 8d4a20e..d365f8c 100644
--- a/build/lib/adapters/outline-view-adapter.js
+++ b/build/lib/adapters/outline-view-adapter.js
@@ -121,6 +121,8 @@ class OutlineViewAdapter {
             return map;
         }, new Map());
         const roots = [];
+        // Need to fix overly-specific names to get nested cquery output^M
+        const possibleParents = allItems.map((item) => (item.outline));^M
         // Put each item within its parent and extract out the roots
         for (const item of allItems) {
             const containerName = item.containerName;
@@ -129,7 +131,7 @@ class OutlineViewAdapter {
                 roots.push(item.outline);
             }
             else {
-                const possibleParents = containers.get(containerName);
+                // const possibleParents = containers.get(containerName);^M
                 let closestParent = OutlineViewAdapter._getClosestParent(possibleParents, child);
                 if (closestParent == null) {
                     closestParent = {
```

I'm sorry for it not being a Pull request. I just really needed my setup to work, and felt like sharing the fix.
