### ISSUE TITLE
Handling repeat auto completion trigger character

### ISSUE THREAD

**Issue by isundaylee** [atom/atom-languageclient#238]
In some languages, auto completion should be triggered after a certain multi-character sequence. Example: `::` and `->` in C++. However, currently the Language Server Protocol does not support settings `triggerCharacters` options with multiple characters. Therefore, many language servers (e.g. [cquery](https://github.com/cquery-project/cquery/blob/38554806d4bede4b83b480d2888b8f15231d5ddb/src/messages/initialize.cc#L46)) choose to only designate the last character in the completion trigger sequence as the trigger character. In the case of `::`, the trigger character will be set to `:`.

In this case, with `atom-languageclient`, typing `std::` would cause the completion to be triggered upon the first `:`, but not upon the second `:`. This would essentially render `::` completion useless, as the first completion request would return an empty result list. 

For the moment (i.e. until LSP adds support for multi-character completion trigger sequences, and language servers catch on), I think the solution that makes sense is to trigger completion on both the first `:` and the second `:`. I have a commit here (https://github.com/isundaylee/atom-languageclient/commit/48c5589) that implements this behavior. But just wanna get an opinion on whether this is the correct direction before sending in the PR.

**Comment by isundaylee** [comment]
Would potentially fix #225, rust-lang-nursery/atom-ide-rust#95, among others

**Comment by damieng** [comment]
Do you want to create a PR here to get it merged in?

**Comment by isundaylee** [comment]
Created #241

**Comment by isundaylee** [comment]
Ah sorry let me fix the tests first.

**Comment by isundaylee** [comment]
Tests fixed.

**Comment by damieng** [comment]
Merged in, will go out in next release.
