### ISSUE TITLE
Provide Support for CodeActions without command

### ISSUE THREAD

**Issue by cdietrich** [atom/atom-languageclient#239]
the current LSP states for code actions

```
result: (Command | CodeAction)[] | null where CodeAction is defined as follows ...
```

it looks like the current adaper only supports the Command return type style.
i am getting following error is server answers with CodeActions directly

```
The accessor 'ExecuteCommandParams.getCommand()' must return a non-null value. Path: $.params.command
```

```
/Users/dietrich/git/solidity-ide/extensions/atom/node_modules/atom-languageclient/build/lib/logger.js:12 Solidity (Solidity Language Server) rpc.sendRequest workspace/executeCommand threw Error: The accessor 'ExecuteCommandParams.getCommand()' must return a non-null value. Path: $.params.command
    at new ResponseError (/Users/dietrich/git/solidity-ide/extensions/atom/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
    at handleResponse (/Users/dietrich/git/solidity-ide/extensions/atom/node_modules/vscode-jsonrpc/lib/main.js:430:48)
    at processMessageQueue (/Users/dietrich/git/solidity-ide/extensions/atom/node_modules/vscode-jsonrpc/lib/main.js:258:17)
    at Immediate._onImmediate (/Users/dietrich/git/solidity-ide/extensions/atom/node_modules/vscode-jsonrpc/lib/main.js:242:13)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by cdietrich** [comment]
here is how the responses look like

```
[{"title":"Change to ^0.4.25","diagnostics":[{"range":{"start":{"line":0,"character":16},"end":{"line":0,"character":23}},"severity":2,"code":"WARNING_SOLIDITY_VERSION_NOT_THE_DEFAULT","source":"Solidity (Solidity Language Server)","message":"Solidity version does not match the default version (^0.4.25)"}],"edit":{"changes":{"file:///Users/dietrich/git/solidity-ide/extensions/atom/lala/demo.sol":[{"range":{"start":{"line":0,"character":16},"end":{"line":0,"character":23}},"newText":"^0.4.25"}]}}}]
```

**Comment by damieng** [comment]
I suspect this was a change in the LSP that is reflected in newer versions of the vscode-language-server library.  The next version of atom-languageclient (currently in master) uses a much newer version - could you try that and see if it works for you?

Just git checkout this repo and then npm i and npm link it.  Then npm link atom-languageclient inside your ide-x package to link the master version across.

**Comment by cdietrich** [comment]
how can i try the new version locally (am not familar with npm so a hint how i can pull the master version of the libary and or link it into my extension would be nice)

**Comment by damieng** [comment]
```
git clone git@github.com:/atom/atom-languageclient.git
cd atom-languageclient
npm i
npm link
cd whatever-ide-package-you-are-using
npm link atom-languageclient
```

Once you're done testing you can just
```
cd whatever-ide-package-you-are-using
npm unlink atom-languageclient
apm i
```

To go back to the previous version of atom-languageclient

Hope that helps.

**Comment by cdietrich** [comment]
Hi,

i am still getting the same error message.
but i am not sure if my change is correct.

you can find my code here: (you need java installed)

```
git clone https://github.com/itemis/xtext-languageserver-example.git
cd xtext-languageserver-example
git checkout cd_codeActionAtom
./gradlew clean build vscodeExtension atomExtension
cd atom-extension
apm link --dev; atom -d "$(pwd)/../demo/"
```

**Comment by cdietrich** [comment]
indeed the new service is only available with even newer dependencies.
and we need some impl for the new service.
unfortunately my typescript knowledge is very limited, so i dont know if something like the following makes sense https://github.com/cdietrich/atom-languageclient/commit/f7a09b34020abdac2523fcaf3d28df97a6aefd90
