### ISSUE TITLE
Completion with snippet with choices

### ISSUE THREAD

**Issue by cdietrich** [atom/atom-languageclient#240]
In VSCode it works fine to have a completion item like

```
{
        "label": "New Greeting (Template)",
        "kind": 15,
        "sortText": "00001",
        "insertTextFormat": 2,
        "textEdit": {
          "range": {
            "start": {
              "line": 4,
              "character": 0
            },
            "end": {
              "line": 4,
              "character": 0
            }
          },
          "newText": "Hello ${1|A,B,C|} from ${2|Other,C,B,Xtext,VSCode,ThisFile,you,Demo|}!"
        }
      }
```

but this does not work with this extension.
(snippet is inserted as plain text)

https://github.com/atom/atom-languageclient/blob/3f8a3ae62281fc89410ff806fe16e03773e5b9f3/lib/adapters/autocomplete-adapter.ts#L330

a snippet with simple placeholders works fine

```
{
        "label": "New Greeting (Template)",
        "kind": 15,
        "sortText": "00001",
        "insertTextFormat": 2,
        "textEdit": {
          "range": {
            "start": {
              "line": 4,
              "character": 0
            },
            "end": {
              "line": 4,
              "character": 0
            }
          },
          "newText": "Hello ${1:foo} from ${2:bar}!"
        }
      }
```

is there something i need to configure to get this running?

**Comment by cdietrich** [comment]
see https://macromates.com/textmate/manual/snippets too

> ${«int»|«choice 1»,…,«choice n»|}

**Comment by cdietrich** [comment]
looks like this is https://github.com/atom/snippets/issues/186

**Comment by damieng** [comment]
Yeah, this package does nothing specific with snippets other than acting as a bridge between language servers and autocomplete so I think that other issue is the place to track it.  Closing it this side.  If further work needs to be done here once that side is addressed we can re-open this issue or create a new one.
