### ISSUE TITLE
If createServerProcess() returns a deferred promise that takes a longer time, atom-languageclient will emit errors when the user dares typing too early

### ISSUE THREAD

**Issue by JonasT** [atom/atom-languageclient#25]
If createServerProcess() returns a deferred promise that takes a longer time, atom-languageclient will emit errors when the user dares typing too early. This seems to happen because the serverCapabilities info from the initialized method aren't set yet, and if you type and the completion mechanism is invoked, there doesn't seem to be a proper check to whether the server process was actually created yet:

```
Uncaught TypeError: Cannot read property 'completionProvider' of undefined
/home/jonas/.atom/packages/language-tethercode/node_modules/atom-languageclient/build/lib/auto-languageclient.js:166
Hide Stack Trace
TypeError: Cannot read property 'completionProvider' of undefined
    at TethercodeLanguageServer.getSuggestions (/home/jonas/.atom/packages/language-tethercode/node_modules/atom-languageclient/build/lib/auto-languageclient.js:166:34)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:325:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:304:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:291:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
To reproduce, make a minimal test plugin which returns a promise as seen here: https://github.com/atom/languageserver-php/blob/master/lib/main.js#L19 .. but which wraps the resolve() call in a setTimeout with a long duration (e.g. 15 seconds).

Then with the plugin active, type a dot or something that will trigger auto completion. If you do that before the resolve() was actually triggered yet, you should see an error.

Edit: to address the obvious question "why would you do that anyway"? While not needed for stdin-based language servers, TCP-based ones have an inherent waiting time (when the server is written as an actual TCP server waiting for incoming connections) because after launching the process you cannot immediately dump into the stdin pipe and wait for it to get parsed, but you need to wait until the process actually opened up the listening socket which can take a few milliseconds or longer. Also, just to find a free port I need to use node.js networking which is asynchronous by design, so that alone makes it almost impossible to instantly guarantee a working language server connection when the `createServerProcess()` function returns. Therefore, I suggest this use case should be fixed and atom-languageclient should expect and deal properly with some asynchronous delay until the server connection is actually ready.

**Comment by damieng** [comment]
yes, this will be fixed in the next update I'm working on where we bring in multiple language server processes to deal with multiple folders.

**Comment by JonasT** [comment]
Neat! This plugin is an amazing addition btw, I was hoping for the Atom editor infrastructure to improve more towards serious IDE use, and official LSP support is something I have been secretly hoping for a while already 🥇

**Comment by damieng** [comment]
Let me know if the latest updates have solved this for you. All promises should now wait for the first instance of the server to start.
