### ISSUE TITLE
No textdocument/didOpen events are sent ever

### ISSUE THREAD

**Issue by JonasT** [atom/atom-languageclient#26]
With my language server implementation, Atom simply sends the initialize and after the server response, nothing happens. I checked against `pyls` to make sure my response looks as expected, and so far I can't make out any obvious error.

Does atom-languageclient maybe fail to send `textdocument/didOpen` for the documents opened already at start? Or if not in general, maybe that happens if the language server takes too long before it booted and the delayed promise for createServerProcess() takes too long to get resolved?

In any case, I'm not getting any events for any documents ever, and if I just send `textDocument/publishDiagnostics` anyway, Atom ignores them..

**Comment by JonasT** [comment]
Here are the JSON objects that are exchanged between atom-languageclient and my server:

`>>` {'params': {'capabilities': {}, 'processId': 1168727, 'rootPath': '/home/jonas/Develop/tethercode-language-server'}, 'method': 'initialize', 'jsonrpc': '2.0', 'id': 0}

`<<` {"result":{"capabilities":{"documentSymbolProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":["."]},"definitionProvider":true,"documentFormattingProvider":false,"signatureHelpProvider":{"triggerCharacters":["("]},"textDocumentSync":2,"referencesProvider":true,"documentRangeFormattingProvider":false}},"jsonrpc":"2.0","id":0}

If I'm typing, there are also auto completion requests. However, if I simply don't touch anything, nothing ever happens further.

**Comment by damieng** [comment]
The onDidOpen is sent in the sync provider - I'm not sure why it's firing for you.

If you're developing a language server from scratch you might be better off starting with a known-good implementation of the client such as VSCode until the atom-languageclient is out of the experimental phase.

**Comment by JonasT** [comment]
It absolutely don't mind if you don't investigate this for now. I guess I'm piling tickets a bit early into this project - if you want I can also stop filing tickets at this stage and file them later when this project is more in a testing and less in a groundwork development phase. (However, I can also keep filing various issues as I stumble across them if you want, whatever you prefer)

I would guess that in this case it's again related to my language server starting up so slowly. I'm happy to use VS Code for now for further tests, I am simply a huge fan of Atom :smile:

**Comment by damieng** [comment]
There was a sequence error where onDidOpen would not be sent for files already open - that has now been fixed. Let me know if you see any more issues with the latest code.

**Comment by JonasT** [comment]
I just updated to the latest version of atom-languageclient to test this (by removing the `node_packages` folder inside the `.atom/packages/language-tethercode` plugin directory and then running `apm install` again in that directory).

Sadly, now I am getting the "Uncaught SyntaxError: Unexpected end of JSON input" error again, despite using TCP sockets which worked fine with git master ~9 days ago. The plugin is unchanged, and the language server works perfectly fine with Visual Studio Code.

Full stack trace:
```
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at StreamMessageReader.onData (/home/jonas/.atom/packages/language-tethercode/node_modules/vscode-jsonrpc/lib/messageReader.js:198:29)
    at Socket.<anonymous> (/home/jonas/.atom/packages/language-tethercode/node_modules/vscode-jsonrpc/lib/messageReader.js:166:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

This is the plugin: https://gitlab.com/tethercode/atom-language-plugin

The TCP connection is successfully opened (I can see this in the language server log) but nothing is ever sent, as if atom-languageclient now reverted to stdin/stdout anyway. (which always used to give me that "Uncaught SyntaxError: Unexpected end of JSON input" error before I changed the plugin code to use TCP sockets)

This is the VS Code plugin: https://gitlab.com/tethercode/vscode-plugin

The language server itself is a bit complicated to install at this point.. since I can't compile to binaries yet. (compiler is unfinished)

**Comment by damieng** [comment]
Sorry about that - did a big cleanup of some of the code paths and broke sockets. If you pull again it should now be working.

Instead of deleting node_packages folder you can actually git clone this repo and then `npm link .` inside it - that will cause the packages to use your local check-out. Then you can update it as you want by just `git pull` in your copy of the repo.

**Comment by JonasT** [comment]
The latest version indeed seems to work fine now, including file synchronization! :heart:

**Comment by damieng** [comment]
Great! :)
