### ISSUE TITLE
Client throws error after receiving a diagnostic message

### ISSUE THREAD

**Issue by eferos93** [atom/atom-languageclient#267]
The client throws the following error after sending a textDocument/publishDiagnostics:

_Notification handler 'textDocument/publishDiagnostics' failed with message: params.diagnostics.map is not a function_

This is the message sent.

```
Content-Length: 383

{"method":"textDocument\/publishDiagnostics","jsonrpc":"2.0","params":[{"diagnostics":
{"severity":1,"range":{"start":{"character":0,"line":3},"end":
{"character":0,"line":3}},"source":"jolie","message":"File not found: prova.iol. Found 
token type STRING, token content 
prova.iol"},"uri":"file:\/\/\/home\/eferos93\/.atom\/packages\/Jolie-ide-atom\/server_temp.ol"}]}

```

I do not understand what is that params.diagnostics.map the error refers to. The message above should respect the LSP specification.

**Comment by Aerijo** [comment]
The server must return an array of diagnostics

https://microsoft.github.io/language-server-protocol/specification#textDocument_publishDiagnostics
