### ISSUE TITLE
Include Apache Camel Language Server in wiki

### ISSUE THREAD

**Issue by apupier** [atom/atom-languageclient#271]
on https://github.com/atom/atom-languageclient/wiki/List-of-Atom-packages-using-Atom-LanguageClient , it woudl be nice to add the Apache Camel support in community languages

`- [Apache Camel](https://github.com/camel-tooling/camel-lsp-client-atom) provides Apache Camel language support using [Apache Camel Language Server](https://github.com/camel-tooling/camel-language-server)`

**Comment by UziTech** [comment]
Development of [atom-languageclient](https://www.npmjs.com/package/atom-languageclient) has officially moved to https://github.com/atom-ide-community/atom-languageclient 🎉 

This has been added to the wiki page at https://github.com/atom-ide-community/atom-languageclient/wiki/List-of-Atom-packages-using-Atom-LanguageClient
