### ISSUE TITLE
Definition provider should highlight only the word under the cursor

### ISSUE THREAD

**Issue by hansonw** [atom/atom-languageclient#28]
Currently, the definition/hyperclick providers query `textDocument/documentHighlight` to figure out what to highlight.

However, in both Nuclide and VSCode (https://github.com/Microsoft/vscode/blob/ff9f7b3baa6052863b55e8b6ef7c7c94d07beddf/src/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.ts#L437), we simply highlight the word under the cursor (in Atom, we use the word regex as defined in the text editor).

This has the benefit of working for providers which don't implement word highlighting.
Also, it looks a bit weird to highlight all the references in the document.

@damieng would you be OK with this change/simplification?

**Comment by damieng** [comment]
Consistency is best!

**Comment by hansonw** [comment]
Cool! I'll send out a PR.
