### ISSUE TITLE
Someway to Get Project Path When Setting Up Server

### ISSUE THREAD

**Issue by keplersj** [atom/atom-languageclient#35]
I'm working on a language client package for [scry](https://github.com/atom-crystal/scry) and I need to be able to start the server binary with the `cwd` as the `projectPath`. There doesn't appear to be an easy and preferred way to get then when starting the server at the moment. Some guidance would be super appreciated.

**Comment by damieng** [comment]
I've added the projectPath to startServerProcess - this should be what you need :)

**Comment by keplersj** [comment]
Perfect thank you!
