### ISSUE TITLE
Hover not working for go-langserver

### ISSUE THREAD

**Issue by fasa123** [atom/atom-languageclient#36]
Hi, I have created an atom consumer package for this Golang server ( https://github.com/sourcegraph/go-langserver/ )

Literally everything works as well as it does in VSCode (which is amazing). Only one thing that does not is the hover/datatip thing. If I have following code:

`package main
import fmt

func main() {
fmt.Println("Hello")
someNumber := 3
fmt.Println(someNumber)
}`

and hover over "Println" (or "someNumber") nothing happens. If I move the cursor over Println and then execute "Nuclide: Datatip toggle" nothing happens. The DevTool (console) doesn't output anything either which is really strange seeing all other features work perfectly fine. Any idea as to what has gone wrong? It cannot be the fault of my consumer since all features (besides the hover) work. It cannot be the fault of the lang-server since it works on the same file under vscode. At least that's my thought process

The implementation of the consumer is 99% copy pasted from the Java package.

**Comment by hansonw** [comment]
Did you declare a `nuclide-datatip.provider` in your package.json? we haven't added that to the sample Java one yet, but we should probably do that.

```
  "consumedServices": {
   ...
    "nuclide-datatip.provider": {
      "versions": {
        "0.0.0": "consumeDatatip"
      }
    }
  }
```

Also, which version of Nuclide do you have installed?

**Comment by fasa123** [comment]
It said "nuclide-datatip" in the package.json after adding the ".provider" it worked. Thanks!

**Comment by damieng** [comment]
Added to our own experimental providers (java, csharp, php)
