### ISSUE TITLE
Problems showing lint diagnostics

### ISSUE THREAD

**Issue by aergonaut** [atom/atom-languageclient#37]
I am trying to develop a plugin to integrate [RLS](https://github.com/rust-lang-nursery/rls) with Atom using this library. My plugin code is here: https://github.com/aergonaut/languageserver-rust

I set up the plugin following the languageserver-java plugin as an example, along with some inspiration from the [vscode-rust](https://github.com/editor-rs/vscode-rust) extension for VSCode, which also uses RLS. Autocomplete works, and so does the Nuclide definitions view and the Hyperclick go-to definition.

The problem I'm having now is that lint diagnostics aren't showing up with Linter.

I have Linter installed and I also made sure to disable the linter-rust plugin. I enabled the "core.debugLSP" setting in my config file so I could get more logging from atom-languageclient about what was going on.

I see the textDocument/publishDiagnostics message get received in the console log and the payload looks like it contains the right information to indicate where the error is.

![img](https://cl.ly/kUYz/Image%202017-05-16%20at%2017.55.36.png)

However, I don't see any of Linter's tooltips popping up in the editor and I don't see any problems reported in Linter's panel.

Is there something simple I'm missing in my package? I'm not sure how to debug further since there's no logging in the code that processes the diagnostics and creates Linter messages.

**Comment by damieng** [comment]
I'd make sure you have the very latest atom-languageclient - npm tends to cache it as I'm not yet bumping the version number.  Best solution is to check out this repo then npm link it until it's officially released.  I only added support for the v2 push/indie api recently.

If that still doesn't work can you try the nuclide diagnostics?  I think you need the UI and store portions enabled - that's what I actually test it with. 

Let me know either way and thanks for picking up a rust language server!  Feel free to ping me here or in the Atom Slack with any comments/ideas.

**Comment by aergonaut** [comment]
Thanks @damieng, I'll try out those recommendations and let you know how it works out.

**Comment by aergonaut** [comment]
@damieng Turning off Linter and using Nuclide Diagnostics, I'm able to see now that it looks like RLS is sending back the path with all the directories up from root doubled. I didn't notice this at first, but I can see it now in the screenshot I posted, and it's displayed more clearly in the Nuclide Diagnostics panel. Thanks for the tip!

Looks to me like I might not be invoking RLS correctly. I'll ping someone over there for help.

**Comment by aergonaut** [comment]
Major derp on my part, I just needed to update RLS! Dug through the issues and found https://github.com/rust-lang-nursery/rls/issues/254 mentioning the same behavior I was seeing.
