### ISSUE TITLE
Logging (including window/logMessage)

### ISSUE THREAD

**Issue by damieng** [atom/atom-languageclient#4]
An LSP server can emit log messages using [window/logMessage](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#window_logMessage)

We also like to emit various diagnostic information from the atom-languageclient library.

It would be great if Atom had a bundled logging UI that Atom and packages could write to that allowed categorisation/sorting/searching copy messages.

**Comment by hansonw** [comment]
We could bundle the Nuclide console with `atom-ide-ui` and use that. It supports categorization (only by provider ATM, but we can probably extend that), filtering, and copying. cc @matthewwithanm

**Comment by laughedelic** [comment]
This was solved by #192
