### ISSUE TITLE
Autocompletion results do not get filtered

### ISSUE THREAD

**Issue by josa42** [atom/atom-languageclient#41]
Currently the autocompletion results do not get filtered or sorted. This behavior is confusing and breaks the tab completion, because the first item is used, not the best matching one.

That's what it currently looks like or me:

![unfiltered](https://cloud.githubusercontent.com/assets/423234/26371589/75afd02c-3ffb-11e7-8de5-aff33c61a1b6.gif)

That's what I would expect:

![filtered](https://cloud.githubusercontent.com/assets/423234/26371596/77e5f7a4-3ffb-11e7-928c-cc70aa5722c6.gif)

I created a PR to implement filtering using [atom/fuzzaldrin](https://github.com/atom/fuzzaldrin).

Which basically does this:

`autocomplete-adapter.js`

```JavaScript
static completionItemsToSuggestions(completionItems: Array<CompletionItem> | CompletionList, request: atom$AutocompleteRequest): Array<atom$AutocompleteSuggestion> {
  return filter(
    (Array.isArray(completionItems) ? completionItems : completionItems.items || [])
      .map(s => AutocompleteAdapter.completionItemToSuggestion(s, request)),
    request.prefix,
    {key: 'filterText'}
  );
}
```

Please let me know what you think.

**Comment by damieng** [comment]
Really the language provider should be re-queried after each keypress to provide the best updated options.

I'm aware of a bug in the Omnisharp provider (language-csharp) that currently prevents this - are you seeing this problem in other language servers too?

**Comment by josa42** [comment]
Thanks for the answer.

I am implementing a client for [`emberwatch/ember-language-server`](https://github.com/emberwatch/ember-language-server). The language provider is re-queried after each keypress. But the results are not getting filtered.

While it sounds absolutely reasonable that the language server should filter the results, at least VSCode seems to filter the results somewhere. This is what I see with same language server in VSCode:

![vscode](https://cloud.githubusercontent.com/assets/423234/26375702/40fe92aa-400a-11e7-9c67-bedb98db02e9.gif)

I may have to dig deeper into this 😃

**Comment by damieng** [comment]
Yeah I'm not opposed to having something like this baked into atom-languageclient although I think people would need to opt-in for when their language server doesn't do it for them.  Otherwise we'll interfere with the process which should technically be yielding more accurate results.  

Let me know how your investigation goes.

**Comment by josa42** [comment]
@damieng Filtering is now solved in the Language Server. Thank you for your input!
