### ISSUE TITLE
Exposing diagnostic 'source' in a better way

### ISSUE THREAD

**Issue by hansonw** [atom/atom-languageclient#47]
Currently the diagnostic source is exposed as `description` in the Indie Linter API, which Nuclide renders by appending (but I think the Indie linter shows this when you hover over the error). It doesn't look great in the diagnostics table.

We should probably figure out a better way to do this. The Indie message API has a (not-for-public-use) `linterName` field: https://github.com/steelbrain/linter/blob/master/docs/types/linter-message-v2.md

Should we lobby to make that part of the public API? I think the implementation would be pretty trivial - the `linterName` would default to the registered name, but if you provide `linterName` in your message it'll override that.

**Comment by damieng** [comment]
Sounds good to me. Do you want to approach them or I can.

**Comment by hansonw** [comment]
I'll file an issue on steelbrain/linter

**Comment by hansonw** [comment]
Closed by #49
