### ISSUE TITLE
Outline view often races with server initialization

### ISSUE THREAD

**Issue by hansonw** [atom/atom-languageclient#48]
Nuclide/atom-ide-ui's outline view queries for a document's outline as soon as it's opened. Since `atom-languageclient` often initializes when the first file is opened, this means that the outline view request can often come before the server's ready.

In the outline view provider (https://github.com/atom/atom-languageclient/blob/master/lib/auto-languageclient.js#L232) the request is skipped if the server isn't active yet. Is it possible to change this to include starting servers as well? I think that'd be sufficient; the outline view provider could wait for the server to start before sending the symbols request.

**Comment by hansonw** [comment]
Something like this I guess, if you don't foresee any issues with it :)

```
  async getActiveOrStartingServer(textEditor: atom$TextEditor): ?Promise<ActiveServer> {
    const finalProjectPath = this.determineProjectPath(textEditor);
    if (finalProjectPath == null) { return null; }

    const server = this.getServer(textEditor, finalProjectPath);
    if (server != null) { return server; }

    return this._startingServerPromises.get(finalProjectPath);
  }
```

I guess we'd have to make sure this does something reasonable if you quickly open and close an editor (thus immediately stopping the starting server).

**Comment by damieng** [comment]
Yeah given that the api's are all promise based this should be fine. I'll add something along those lines now. 

As for the start/stop - I was thinking of putting a package-configurable delay-before-shutdown option with perhaps a default based on how long it takes to start the process up again.
