### ISSUE TITLE
Document synchronization actions are triggered for unsupported languages

### ISSUE THREAD

**Issue by janos-ss** [atom/atom-languageclient#56]
The language client gets activated when working with files whose language matches `getGrammarScopes`. But once activated, document synchronization actions are triggered for all files, because the editor selector function passed to `DocumentSyncAdapter` disregards `getGrammarScopes`.

**Comment by damieng** [comment]
I'm not sure this is actually a bug - it's not clear from the language spec.

Think of the scenario such as in Java where although the language server only supports enhanced functionality in .java files but may well want to know and change it's behavior for a variety of other files such as .xml which may describe the build process or other important configuration.

**Comment by hansonw** [comment]
FWIW VSCode's language client seems to enforce its `documentSelector` on all document events: https://github.com/Microsoft/vscode-languageserver-node/blob/6dbda9039f5702abaf959076596e187a3c03ddd0/client/src/client.ts#L594

I think for the Java/XML use case you'd have to explicitly register to both .java and .xml files.

**Comment by damieng** [comment]
Yeah that makes sense.  I've added a few comments to the PR. Thanks.
