### ISSUE TITLE
Document renames are not synced

### ISSUE THREAD

**Issue by hansonw** [atom/atom-languageclient#58]
While we're on the subject of document syncing, it appears that renaming a document doesn't send any events :D I think the LSP intends for you to pass these along as a close + re-open with the new URI.

**Comment by damieng** [comment]
I was expecting that a rename would be detected by the https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#workspace_didChangeWatchedFiles message.

We need https://github.com/atom/atom/pull/14853 to land before that.

You might be right about file close/open as well though.

**Comment by hansonw** [comment]
I did some digging into what VSCode does and basically they have no concept of renaming open buffers - when you rename a file in the file tree, it closes the old buffer and re-opens it. I confirmed that in the language server, you get corresponding close / open events.

FWIW our Nuclide adapter does the same thing. I'll implement it :)

**Comment by damieng** [comment]
Awesome, thanks!
