### ISSUE TITLE
How to use this package in atom ? 

### ISSUE THREAD

**Issue by rwatts3** [atom/atom-languageclient#62]
Greetings, 

I have installed this package as well as `atom/ide-typescript`. However when I open a project containing javascript or typescript, nothing seems to happen. Am I supposed to manually start a language server ? 

Is there any documentation on how to use this package properly?

**Comment by damieng** [comment]
This package is not usable by Atom users directly - it is for package authors wanting to integrate a language server with Atom.

There are a few packages already using it if you want to try them out. We expect more soon after this initiative officially launches.

https://github.com/atom/ide-typescript
https://github.com/atom/ide-php
https://github.com/atom/ide-csharp
https://github.com/atom/ide-java
