### ISSUE TITLE
Autocomplete include parameters

### ISSUE THREAD

**Issue by zaaack** [atom/atom-languageclient#64]
I think this can make an option since autocomplete in atom cannot complete parameters in the fly like vscode.

**Comment by damieng** [comment]
I don't understand the issue here - can you provide some more detail and perhaps some examples?

**Comment by zaaack** [comment]
Here is ide-typescript: 
![Untitled.gif](https://i.loli.net/2017/07/18/596d7b5b14fe8.gif)
Here is vscode:
![Untitled3.gif](https://i.loli.net/2017/07/18/596d7b5b0baa2.gif)

 And in atom the autocomplete disappeared I can't find the parameter definitions anymore, some package will autocomplete the whole parameter list like:
```js
a.toString(radix? number | undefined)
```
and auto select parameters, so you can delete them all convenient.

**Comment by hansonw** [comment]
Autocompleting the whole parameter list is tracked by #31.
The VSCode gif is actually implemented by the 'signatureHelp' API, and is tracked by #9.
Closing this issue as you can follow along in the other two :)
