### ISSUE TITLE
completionItem/resolve

### ISSUE THREAD

**Issue by damieng** [atom/atom-languageclient#7]
Auto completion items may not be fully completed during the initial completion request and can be further resolved to fill in the missing details by calling [completionItem/resolve](https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#completionItem_resolve).

## Challenges
- Autocomplete+ does not have a hook for this right now
- Autocomplete+ would need a new API for this
- Find a language server that requires this

Activate if `capabilities.completionOptions.resolveProvider === true`

**Comment by kdvolder** [comment]
Just FYI, this discussion may be relevant: 

https://github.com/Microsoft/language-server-protocol/issues/275

**Comment by damieng** [comment]
https://github.com/atom/autocomplete-plus/pull/925
