### ISSUE TITLE
Add restart language server command

### ISSUE THREAD

**Issue by zaaack** [atom/atom-languageclient#71]
Once a server freezes, we have to disable and enable the package, can we add an atom command to restart language server? I know this might be able to implement in each package, but it's a frequent use case and hoping this is a default behavior.

**Comment by daviwil** [comment]
We're adding a `AutoLanguageClient.restartAllServers()` command in PR #172 so that individual language packages can add a restart command to the command palette for their servers.  Do you think that's sufficient to resolve this issue?

**Comment by zaaack** [comment]
Yes, thanks!
