### ISSUE TITLE
Incremental edits should be sent to the server in reverse order (textDocument/didChange/contentChanges)

### ISSUE THREAD

**Issue by zaaack** [atom/atom-languageclient#72]
I create a package [ide-reason](https://github.com/zaaack/atom-ide-reason) using the same [language server](https://github.com/freebroccolo/ocaml-language-server) of the vs code version. But there is a strange bug, here is trigger condition:
1. delete two line at the same time.
2. the first line contains '\n' character and any number of characters before it.

![untitled3](https://user-images.githubusercontent.com/5233940/28496039-2b6d3316-6f93-11e7-8fa3-4088080b737f.gif)

I think it is the same issue in code formatting: https://github.com/reasonml/reasonml.github.io/pull/24#issuecomment-316367975

I guess this might be caused by "onDidChange"'s change range is handled serially in the server but the ranges of a change event in client are based on the old document. I read the protocol, but didn't see anything about this, not sure about which way is right.

**Comment by zaaack** [comment]
This issue might be relevant: https://github.com/atom/atom-languageclient/issues/29

**Comment by damieng** [comment]
Hey @hansonw do you have any ideas what might be causing this?

**Comment by hansonw** [comment]
Sure, I can take a look. The stock VSCode language server doesn't support incremental syncing, so I'm surprised this kind of issue occurs....

**Comment by hansonw** [comment]
OK, this is an issue with `ocaml-language-service`. It looks like the language server always applies changes without looking at the order; this isn't safe because the LSP doesn't specify an ordering for `contentChanges`. `atom-languageclient` chooses to send changes in document order, but really the server is expecting them in **reverse** order. https://github.com/freebroccolo/ocaml-language-server/blob/683656b5fb6e3239ce38ddf03600be78c1f70079/src/server/session/synchronizer.ts#L45

cc @arxanas, should the ocaml language server be sorting the edits here?

**Comment by zaaack** [comment]
@hansonw What do you mean about `in reverse order`? All I notice is that `ocaml-language-server` apply changes one-by-one, so each change's position based on last change, if last change removed a line, then the following change's line number will not match the sent changes by `atom-languageclient`, because they are based on the same document.

**Comment by zaaack** [comment]
And as @chenglou mentioned ( https://github.com/reasonml/reasonml.github.io/pull/24#issuecomment-317195426 ), [ide-csharp](https://github.com/atom/ide-csharp)' user might have this problem, too.

**Comment by hansonw** [comment]
@zaaack It's not well-defined in the LSP what order `contentChanges` should be applied in when there are multiple changes. I guess we're assuming that the server sorts them lexicographically and applies them backwards, so changes won't affect each other.

Looking at other language server implementations, it doesn't appear that any of them actually do any sorting - so I'll go ahead and make the change in `atom-languageclient` to provide them in reverse order. (Though I think the protocol spec could provide some clarification here.)

**Comment by arxanas** [comment]
I wrote the original implementation of text document syncing for ocaml-language-server and it just slipped my mind to worry about edits in the wrong order! I wasn't thinking about anything in particular regarding who should sort the edits.

It's probably the language server that should be sorting the edits, but in practice I suppose both the client and the server will be sorting it just in case the other doesn't. cc @ljw1004: maybe we ought to sort the edits for Hack to ensure compatibility across multiple editors.

**Comment by ljw1004** [comment]
As @hansonw says, the LSP is underspecified in this area.

LSP says this about TextEdit:
> If multiple TextEdits are applied to a text document, all text edits describe changes made to the initial document version. Execution-wise text edits should be applied from the bottom to the top of the text document. Overlapping text edits are not supported.

You'd think for symmetry that LSP would have the same rules for TextDocumentContentChangeEvent. (i.e. as you say, the language servers should do the sorting).

But then as @hansonw says, the existing body of LSP implementations don't seem to do that sort.

I reckon that (1) LSP should be amended, (2) VSCode and Atom should do the sort themselves to be compatible with LSP servers that don't yet do the newly specified behavior, (3) over time LSP servers should change to the newly specified behavior.
