### ISSUE TITLE
Diagnostics aren't shown anywhere in Atom

### ISSUE THREAD

**Issue by JonasT** [atom/atom-languageclient#73]
I am working on an experimental package for my homebrew language which uses atom-languageclient to communicate with my self-written language server for it.

It loads up fine and from the logs I can see Atom synchronizing all the workspace contents as expected and the language server responding with `textdocument/publishDiagnostics`. However, visually in Atom if I go to any affected lines I can't see any trace of a marking that would indicate a reported issue. In Visual Studio Code for which I also made a test plugin, everything shows up fine.

The plugin code I use for Atom is pretty simple and doesn't do much more except setup the TCP connection: https://gitlab.com/tethercode/atom-language-plugin/blob/master/lib/main.js

Edit: this is one of the JSON messages ignored by Atom:

```
Content-Length: 385
Content-Type: application/vscode-jsonrpc; charset=utf8

{"method":"textDocument/publishDiagnostics","jsonrpc":"2.0","params":{"uri":"file:///home/jonas/Develop/tethercode-language-server/workspace.tc","diagnostics":[{"source":"tethercc","message":"undefined identifier 'replace': no such variable known in current scope","range":{"start":{"column":26,"line":154},"end":{"column":0,"line":155}},"severity":1,"code":"Eundefined-identifier"}]}}
```

**Comment by damieng** [comment]
If you open up the Atom dev tools and type;

`atom.config.set('core.debugLSP', true)`

You should see all the messages going back and forth which can help diagnose these issues.

**Comment by JonasT** [comment]
Is the user supposed to install a linter package separately to make it show up? This isn't really clear from the atom-languageclient readme description.. I tried installing the "linter" package but it didn't help in making anything show up.

Since it works fine in Visual Studio Code I would assume it's more likely to be something wrong with how my plugin is set up, and not so much with what the language server sends protocol-wise.

**Comment by damieng** [comment]
You will need to install the `atom-ide-ui` package for the user interface to light-up and start displaying diagnostics, outline views, go to definition, code formatting etc.

I'll add this information to the README, sorry for the confusion.

**Comment by JonasT** [comment]
Should I make this a dependency for my language package? Arguably a user would expect this all to be automatically done behind the scenes when installing a language-XYZ support package, no? I didn't see this as a dependency in any of the other language packages though. What does the average Atom user expect here?

**Comment by damieng** [comment]
We're going to be tackling that separately when we get closer to launch.

**Comment by JonasT** [comment]
Ok, I verified now that with `atom-ide-ui` it works as expected and I get nice error annotations <3 thanks for the help
