### ISSUE TITLE
textDocument/hover

### ISSUE THREAD

**Issue by damieng** [atom/atom-languageclient#8]
The [textDocument/hover](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_hover) api allows additional information about a section of the document to be displayed in a hover/tool-tip style fashion.

## Challenges
- Nuclide has datatips for this but expect a react component not markdown as returned by LSP

**Comment by hansonw** [comment]
Hopefully I can get this checked in today, will update here :)

**Comment by hansonw** [comment]
I landed this in https://github.com/facebook/nuclide/commit/20140733bc0608a6fee292b7a15c9cdf1776adfe!

![screen shot 2017-04-04 at 5 18 10 pm](https://cloud.githubusercontent.com/assets/577378/24721396/18cc4420-19f5-11e7-95b9-2ba68ac53301.png)

I can work on a PR to integrate with these if you don't get around to it.
