### ISSUE TITLE
Outline and hovers don't seem to be working doesn't trigger any breakpoints

### ISSUE THREAD

**Issue by rcjsuen** [atom/atom-languageclient#80]
Hi, I have a language server that responds to `textDocument/documentSymbol` and `textDocument/hover`. However, when I invoke Alt+O in my editor, nothing seems to happen. If I hit Ctrl+Space, the debugger will hit [`getSuggestions`](https://github.com/atom/atom-languageclient/blob/d09da17f4ef7dea8c74749d2c122e08a5c7b7da6/lib/auto-languageclient.js#L202-L208) but hitting Alt+O doesn't break on [`getOutline`](https://github.com/atom/atom-languageclient/blob/d09da17f4ef7dea8c74749d2c122e08a5c7b7da6/lib/auto-languageclient.js#L238-L244). Hovering in my editor also does not break on [`getDatatip`](https://github.com/atom/atom-languageclient/blob/d09da17f4ef7dea8c74749d2c122e08a5c7b7da6/lib/auto-languageclient.js#L287-L293).

Besides code completion, my diagnostics are being displayed in the editor and using Ctrl+Alt+C formats my code just fine.

Here is the relevant portion of my `package.json` file. Am I doing something wrong here?
```JavaScript
{
  "consumedServices": {
    "linter-indie": {
      "versions": {
        "2.0.0": "consumeLinterV2"
      }
    },
    "datatip": {
      "versions": {
        "0.0.0": "consumeDatatip"
      }
    }
  },
  "providedServices": {
    "autocomplete.provider": {
      "versions": {
        "2.0.0": "provideAutocomplete"
      }
    },
    "nuclide-code-format.provider": {
      "versions": {
        "0.0.0": "provideCodeFormat"
      }
    },
    "definitions": {
      "versions": {
        "0.0.0": "provideDefinitions"
      }
    },
    "outline-view": {
      "versions": {
        "0.0.0": "provideOutlines"
      }
    }
  }
}
```

**Comment by damieng** [comment]
Sorry, datatip, definitions and outline-view etc. should be version "0.1.0"   (linter-indie, autocomplete.provider and nuclide-code-format.provider are correct as they are)

I changed these over from the previous nuclide service names a couple of days ago but missed the version numbers.

**Comment by rcjsuen** [comment]
Thanks for the tip, that did it! `textDocument/definition`, `textDocument/documentSymbol`, and `textDocument/hover` are all working now.

Do I need to do anything to get `textDocument/documentHighlight` working? Clicking inside the word or highlighting the word itself does not highlight the other occurrences in the file.

**Comment by damieng** [comment]
Holding down control and then hovering over a word should trigger the highlighting of all the other refererences.  Clicking it should go to the definition.

**Comment by rcjsuen** [comment]
Thanks, Ctrl+Clicking gets the other references underlined!
