### ISSUE TITLE
textDocument/signatureHelp

### ISSUE THREAD

**Issue by damieng** [atom/atom-languageclient#9]
An LSP server can reveal additional information about a function via the [textDocument/signatureHelp](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_signatureHelp) call.

We should write a text or block decoration that exposes these as appropriate.

**Comment by fasa123** [comment]
Is there any reason not to use the Nuclide Datatip? Sorry for the question I am just curious since this, together with the other already implemented functions, is one of the essentials of a language-server client. The rest is, to me, more or less just extra sugar.

**Comment by damieng** [comment]
We're currently using the Nuclide Datatip for for the hover api call when you hover the mouse over. I think a text or block decoration would work better but am open to suggestions on how they can live side by side in the datatip scenario.

**Comment by fasa123** [comment]
![](https://github.com/fasa123/atom-signaturehelper/blob/master/screen.png?raw=true)

https://github.com/fasa123/atom-signaturehelper 
Obviously it needs some work but it works fine

**Comment by hansonw** [comment]
I've put up what I have so far over at https://github.com/facebook-atom/atom-ide-ui/blob/master/docs/signature-help.md.

UI still needs some attention but it's working with the TypeScript server - will put up a PR for the language client side tomorrow.
