### ISSUE TITLE
Proposal : IDE-HTML

### ISSUE THREAD

**Issue by rwatts3** [atom/atom-languageclient#94]
Greetings, 

I am in the process of reviewing and potentially contributing an `ide-html` package. 
With that said , per our previous conversation with the ide-namespace. I am wondering if this is on the list for the atom team to contribute. 

I'm happy to release the initial version under `atom-ide-html`. And transfer the project to later be consumed under `ide-html` . Or avoid the project altogether if there is a plan in place to implement it. 

-V/R

Ryan

**Comment by damieng** [comment]
I think we'll be taking on an ide-html project soon. As you saw getting one up and running with the basics is quite easy. The fine tuning and support are where things can get difficult quickly.
