### ISSUE TITLE
Reloading editor window leaves a language server running

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom-languageclient#96]
Repro:

#### Set up two node modules that have symlinks to each other
1. Install `ide-typescript`
2. Clone [`text-buffer`](https://github.com/atom/text-buffer).
3. Clone [`node-pathwatcher`](https://github.com/atom/node-pathwatcher).
4. In the `text-buffer` repo, run `npm install && npm link`
5. In the `node-pathwatcher` repo, run `npm install && npm link && npm link text-buffer`
6. In the `text-buffer` repo, run `npm link pathwatcher`

#### Work on one of the modules in Atom
7. Open the `text-buffer` folder in Atom.
8. Open a JavaScript file, e.g. `src/display-layer.js`
9. Try to command-click on a variable, see the spinner cursor.
10. See one `Atom Helper` process running `language-server-stdio` using about 100% CPU
11. Reload the editor window with the `Window: Reload` command
12. Try again to command-click on a variable.
13. See two `Atom Helper` processes running `language-server-stdio`, each using about 100% CPU

**Comment by damieng** [comment]
This is going to require that Atom support an async promise based system for deactivating packages.

**Comment by hansonw** [comment]
I think it's sufficient to add a `process.on('exit')` hook to kill child processes?
We've had to do this in Nuclide before to prevent this exact issue. I just verified that the hook does get triggered when Atom is reloaded.
https://github.com/facebook/nuclide/blob/master/pkg/nuclide-task/lib/bootloader.js#L67
